package com.database.bean;

import java.util.Date;

public class Alipayasynchronouslog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.notify_time
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Date notifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.notify_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String notifyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.notify_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String notifyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.sign_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String signType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.sign
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String sign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.out_trade_no
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String outTradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.subject
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.payment_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String paymentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.trade_no
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String tradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.trade_status
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String tradeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.seller_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String sellerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.seller_email
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String sellerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.buyer_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String buyerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.buyer_email
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String buyerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.total_fee
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String totalFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.quantity
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.price
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.body
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String body;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.gmt_create
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.gmt_payment
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Date gmtPayment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.is_total_fee_adjust
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Integer isTotalFeeAdjust;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.use_coupon
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Integer useCoupon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.discount
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.gmt_close
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Date gmtClose;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.business_scene
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String businessScene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.out_channel_inst
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private String outChannelInst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column alipayasynchronouslog.userId
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.id
	 * @return  the value of alipayasynchronouslog.id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.id
	 * @param id  the value for alipayasynchronouslog.id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.notify_time
	 * @return  the value of alipayasynchronouslog.notify_time
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Date getNotifyTime() {
		return notifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.notify_time
	 * @param notifyTime  the value for alipayasynchronouslog.notify_time
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setNotifyTime(Date notifyTime) {
		this.notifyTime = notifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.notify_type
	 * @return  the value of alipayasynchronouslog.notify_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getNotifyType() {
		return notifyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.notify_type
	 * @param notifyType  the value for alipayasynchronouslog.notify_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setNotifyType(String notifyType) {
		this.notifyType = notifyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.notify_id
	 * @return  the value of alipayasynchronouslog.notify_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getNotifyId() {
		return notifyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.notify_id
	 * @param notifyId  the value for alipayasynchronouslog.notify_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setNotifyId(String notifyId) {
		this.notifyId = notifyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.sign_type
	 * @return  the value of alipayasynchronouslog.sign_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getSignType() {
		return signType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.sign_type
	 * @param signType  the value for alipayasynchronouslog.sign_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setSignType(String signType) {
		this.signType = signType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.sign
	 * @return  the value of alipayasynchronouslog.sign
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.sign
	 * @param sign  the value for alipayasynchronouslog.sign
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setSign(String sign) {
		this.sign = sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.out_trade_no
	 * @return  the value of alipayasynchronouslog.out_trade_no
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getOutTradeNo() {
		return outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.out_trade_no
	 * @param outTradeNo  the value for alipayasynchronouslog.out_trade_no
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.subject
	 * @return  the value of alipayasynchronouslog.subject
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.subject
	 * @param subject  the value for alipayasynchronouslog.subject
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.payment_type
	 * @return  the value of alipayasynchronouslog.payment_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getPaymentType() {
		return paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.payment_type
	 * @param paymentType  the value for alipayasynchronouslog.payment_type
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.trade_no
	 * @return  the value of alipayasynchronouslog.trade_no
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getTradeNo() {
		return tradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.trade_no
	 * @param tradeNo  the value for alipayasynchronouslog.trade_no
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.trade_status
	 * @return  the value of alipayasynchronouslog.trade_status
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getTradeStatus() {
		return tradeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.trade_status
	 * @param tradeStatus  the value for alipayasynchronouslog.trade_status
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setTradeStatus(String tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.seller_id
	 * @return  the value of alipayasynchronouslog.seller_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getSellerId() {
		return sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.seller_id
	 * @param sellerId  the value for alipayasynchronouslog.seller_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.seller_email
	 * @return  the value of alipayasynchronouslog.seller_email
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getSellerEmail() {
		return sellerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.seller_email
	 * @param sellerEmail  the value for alipayasynchronouslog.seller_email
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setSellerEmail(String sellerEmail) {
		this.sellerEmail = sellerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.buyer_id
	 * @return  the value of alipayasynchronouslog.buyer_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getBuyerId() {
		return buyerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.buyer_id
	 * @param buyerId  the value for alipayasynchronouslog.buyer_id
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setBuyerId(String buyerId) {
		this.buyerId = buyerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.buyer_email
	 * @return  the value of alipayasynchronouslog.buyer_email
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getBuyerEmail() {
		return buyerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.buyer_email
	 * @param buyerEmail  the value for alipayasynchronouslog.buyer_email
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setBuyerEmail(String buyerEmail) {
		this.buyerEmail = buyerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.total_fee
	 * @return  the value of alipayasynchronouslog.total_fee
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getTotalFee() {
		return totalFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.total_fee
	 * @param totalFee  the value for alipayasynchronouslog.total_fee
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setTotalFee(String totalFee) {
		this.totalFee = totalFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.quantity
	 * @return  the value of alipayasynchronouslog.quantity
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.quantity
	 * @param quantity  the value for alipayasynchronouslog.quantity
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.price
	 * @return  the value of alipayasynchronouslog.price
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.price
	 * @param price  the value for alipayasynchronouslog.price
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.body
	 * @return  the value of alipayasynchronouslog.body
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getBody() {
		return body;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.body
	 * @param body  the value for alipayasynchronouslog.body
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setBody(String body) {
		this.body = body;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.gmt_create
	 * @return  the value of alipayasynchronouslog.gmt_create
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.gmt_create
	 * @param gmtCreate  the value for alipayasynchronouslog.gmt_create
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.gmt_payment
	 * @return  the value of alipayasynchronouslog.gmt_payment
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Date getGmtPayment() {
		return gmtPayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.gmt_payment
	 * @param gmtPayment  the value for alipayasynchronouslog.gmt_payment
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setGmtPayment(Date gmtPayment) {
		this.gmtPayment = gmtPayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.is_total_fee_adjust
	 * @return  the value of alipayasynchronouslog.is_total_fee_adjust
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Integer getIsTotalFeeAdjust() {
		return isTotalFeeAdjust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.is_total_fee_adjust
	 * @param isTotalFeeAdjust  the value for alipayasynchronouslog.is_total_fee_adjust
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setIsTotalFeeAdjust(Integer isTotalFeeAdjust) {
		this.isTotalFeeAdjust = isTotalFeeAdjust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.use_coupon
	 * @return  the value of alipayasynchronouslog.use_coupon
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Integer getUseCoupon() {
		return useCoupon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.use_coupon
	 * @param useCoupon  the value for alipayasynchronouslog.use_coupon
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setUseCoupon(Integer useCoupon) {
		this.useCoupon = useCoupon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.discount
	 * @return  the value of alipayasynchronouslog.discount
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.discount
	 * @param discount  the value for alipayasynchronouslog.discount
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setDiscount(String discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.gmt_close
	 * @return  the value of alipayasynchronouslog.gmt_close
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Date getGmtClose() {
		return gmtClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.gmt_close
	 * @param gmtClose  the value for alipayasynchronouslog.gmt_close
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setGmtClose(Date gmtClose) {
		this.gmtClose = gmtClose;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.business_scene
	 * @return  the value of alipayasynchronouslog.business_scene
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getBusinessScene() {
		return businessScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.business_scene
	 * @param businessScene  the value for alipayasynchronouslog.business_scene
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setBusinessScene(String businessScene) {
		this.businessScene = businessScene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.out_channel_inst
	 * @return  the value of alipayasynchronouslog.out_channel_inst
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public String getOutChannelInst() {
		return outChannelInst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.out_channel_inst
	 * @param outChannelInst  the value for alipayasynchronouslog.out_channel_inst
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setOutChannelInst(String outChannelInst) {
		this.outChannelInst = outChannelInst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column alipayasynchronouslog.userId
	 * @return  the value of alipayasynchronouslog.userId
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column alipayasynchronouslog.userId
	 * @param userid  the value for alipayasynchronouslog.userId
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}