package com.database.bean;

import java.util.Date;
import java.util.List;

public class Area {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.id
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.area_code
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private String areaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.pid
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.name
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.effective_date
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private Date effectiveDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.expiry_date
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private Date expiryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ind_area.mid
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	private Integer mid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.id
	 * @return  the value of ind_area.id
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.id
	 * @param id  the value for ind_area.id
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.area_code
	 * @return  the value of ind_area.area_code
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public String getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.area_code
	 * @param areaCode  the value for ind_area.area_code
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.pid
	 * @return  the value of ind_area.pid
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.pid
	 * @param pid  the value for ind_area.pid
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.name
	 * @return  the value of ind_area.name
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.name
	 * @param name  the value for ind_area.name
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.effective_date
	 * @return  the value of ind_area.effective_date
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public Date getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.effective_date
	 * @param effectiveDate  the value for ind_area.effective_date
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.expiry_date
	 * @return  the value of ind_area.expiry_date
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public Date getExpiryDate() {
		return expiryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.expiry_date
	 * @param expiryDate  the value for ind_area.expiry_date
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ind_area.mid
	 * @return  the value of ind_area.mid
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public Integer getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ind_area.mid
	 * @param mid  the value for ind_area.mid
	 * @mbggenerated  Sat Oct 10 13:49:44 GMT+08:00 2015
	 */
	public void setMid(Integer mid) {
		this.mid = mid;
	}
	
	private List<Area> subs;

	public List<Area> getSubs() {
		return subs;
	}

	public void setSubs(List<Area> subs) {
		this.subs = subs;
	}
}