package com.database.bean;

import java.util.Date;

public class ContentPlugin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_id
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_name
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String contentpluginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_nodeid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginNodeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_articleid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginArticleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_userid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_insertdate
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Date contentpluginInsertdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_must
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String contentpluginMust;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_arbitrarily
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String contentpluginArbitrarily;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_not
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String contentpluginNot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_searchsource
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginSearchsource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_sort
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginSort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_fromsource
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String contentpluginFromsource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_pagesize
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginPagesize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_starttime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Date contentpluginStarttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_endtime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Date contentpluginEndtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_repeatflag
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginRepeatflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_repeattime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Integer contentpluginRepeattime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_updatetime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Date contentpluginUpdatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_inserttime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private Date contentpluginInserttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.str_type
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String strType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_contentplugin.contentplugin_searchcondition
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	private String contentpluginSearchcondition;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_id
	 * @return  the value of know_contentplugin.contentplugin_id
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginId() {
		return contentpluginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_id
	 * @param contentpluginId  the value for know_contentplugin.contentplugin_id
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginId(Integer contentpluginId) {
		this.contentpluginId = contentpluginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_name
	 * @return  the value of know_contentplugin.contentplugin_name
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getContentpluginName() {
		return contentpluginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_name
	 * @param contentpluginName  the value for know_contentplugin.contentplugin_name
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginName(String contentpluginName) {
		this.contentpluginName = contentpluginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_nodeid
	 * @return  the value of know_contentplugin.contentplugin_nodeid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginNodeid() {
		return contentpluginNodeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_nodeid
	 * @param contentpluginNodeid  the value for know_contentplugin.contentplugin_nodeid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginNodeid(Integer contentpluginNodeid) {
		this.contentpluginNodeid = contentpluginNodeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_articleid
	 * @return  the value of know_contentplugin.contentplugin_articleid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginArticleid() {
		return contentpluginArticleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_articleid
	 * @param contentpluginArticleid  the value for know_contentplugin.contentplugin_articleid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginArticleid(Integer contentpluginArticleid) {
		this.contentpluginArticleid = contentpluginArticleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_userid
	 * @return  the value of know_contentplugin.contentplugin_userid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginUserid() {
		return contentpluginUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_userid
	 * @param contentpluginUserid  the value for know_contentplugin.contentplugin_userid
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginUserid(Integer contentpluginUserid) {
		this.contentpluginUserid = contentpluginUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_insertdate
	 * @return  the value of know_contentplugin.contentplugin_insertdate
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Date getContentpluginInsertdate() {
		return contentpluginInsertdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_insertdate
	 * @param contentpluginInsertdate  the value for know_contentplugin.contentplugin_insertdate
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginInsertdate(Date contentpluginInsertdate) {
		this.contentpluginInsertdate = contentpluginInsertdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_must
	 * @return  the value of know_contentplugin.contentplugin_must
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getContentpluginMust() {
		return contentpluginMust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_must
	 * @param contentpluginMust  the value for know_contentplugin.contentplugin_must
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginMust(String contentpluginMust) {
		this.contentpluginMust = contentpluginMust;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_arbitrarily
	 * @return  the value of know_contentplugin.contentplugin_arbitrarily
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getContentpluginArbitrarily() {
		return contentpluginArbitrarily;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_arbitrarily
	 * @param contentpluginArbitrarily  the value for know_contentplugin.contentplugin_arbitrarily
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginArbitrarily(String contentpluginArbitrarily) {
		this.contentpluginArbitrarily = contentpluginArbitrarily;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_not
	 * @return  the value of know_contentplugin.contentplugin_not
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getContentpluginNot() {
		return contentpluginNot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_not
	 * @param contentpluginNot  the value for know_contentplugin.contentplugin_not
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginNot(String contentpluginNot) {
		this.contentpluginNot = contentpluginNot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_searchsource
	 * @return  the value of know_contentplugin.contentplugin_searchsource
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginSearchsource() {
		return contentpluginSearchsource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_searchsource
	 * @param contentpluginSearchsource  the value for know_contentplugin.contentplugin_searchsource
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginSearchsource(Integer contentpluginSearchsource) {
		this.contentpluginSearchsource = contentpluginSearchsource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_sort
	 * @return  the value of know_contentplugin.contentplugin_sort
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginSort() {
		return contentpluginSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_sort
	 * @param contentpluginSort  the value for know_contentplugin.contentplugin_sort
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginSort(Integer contentpluginSort) {
		this.contentpluginSort = contentpluginSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_fromsource
	 * @return  the value of know_contentplugin.contentplugin_fromsource
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getContentpluginFromsource() {
		return contentpluginFromsource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_fromsource
	 * @param contentpluginFromsource  the value for know_contentplugin.contentplugin_fromsource
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginFromsource(String contentpluginFromsource) {
		this.contentpluginFromsource = contentpluginFromsource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_pagesize
	 * @return  the value of know_contentplugin.contentplugin_pagesize
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginPagesize() {
		return contentpluginPagesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_pagesize
	 * @param contentpluginPagesize  the value for know_contentplugin.contentplugin_pagesize
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginPagesize(Integer contentpluginPagesize) {
		this.contentpluginPagesize = contentpluginPagesize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_starttime
	 * @return  the value of know_contentplugin.contentplugin_starttime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Date getContentpluginStarttime() {
		return contentpluginStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_starttime
	 * @param contentpluginStarttime  the value for know_contentplugin.contentplugin_starttime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginStarttime(Date contentpluginStarttime) {
		this.contentpluginStarttime = contentpluginStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_endtime
	 * @return  the value of know_contentplugin.contentplugin_endtime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Date getContentpluginEndtime() {
		return contentpluginEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_endtime
	 * @param contentpluginEndtime  the value for know_contentplugin.contentplugin_endtime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginEndtime(Date contentpluginEndtime) {
		this.contentpluginEndtime = contentpluginEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_repeatflag
	 * @return  the value of know_contentplugin.contentplugin_repeatflag
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginRepeatflag() {
		return contentpluginRepeatflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_repeatflag
	 * @param contentpluginRepeatflag  the value for know_contentplugin.contentplugin_repeatflag
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginRepeatflag(Integer contentpluginRepeatflag) {
		this.contentpluginRepeatflag = contentpluginRepeatflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_repeattime
	 * @return  the value of know_contentplugin.contentplugin_repeattime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getContentpluginRepeattime() {
		return contentpluginRepeattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_repeattime
	 * @param contentpluginRepeattime  the value for know_contentplugin.contentplugin_repeattime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginRepeattime(Integer contentpluginRepeattime) {
		this.contentpluginRepeattime = contentpluginRepeattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_updatetime
	 * @return  the value of know_contentplugin.contentplugin_updatetime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Date getContentpluginUpdatetime() {
		return contentpluginUpdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_updatetime
	 * @param contentpluginUpdatetime  the value for know_contentplugin.contentplugin_updatetime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginUpdatetime(Date contentpluginUpdatetime) {
		this.contentpluginUpdatetime = contentpluginUpdatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_inserttime
	 * @return  the value of know_contentplugin.contentplugin_inserttime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Date getContentpluginInserttime() {
		return contentpluginInserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_inserttime
	 * @param contentpluginInserttime  the value for know_contentplugin.contentplugin_inserttime
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginInserttime(Date contentpluginInserttime) {
		this.contentpluginInserttime = contentpluginInserttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.str_type
	 * @return  the value of know_contentplugin.str_type
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getStrType() {
		return strType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.str_type
	 * @param strType  the value for know_contentplugin.str_type
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setStrType(String strType) {
		this.strType = strType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_contentplugin.contentplugin_searchcondition
	 * @return  the value of know_contentplugin.contentplugin_searchcondition
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getContentpluginSearchcondition() {
		return contentpluginSearchcondition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_contentplugin.contentplugin_searchcondition
	 * @param contentpluginSearchcondition  the value for know_contentplugin.contentplugin_searchcondition
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setContentpluginSearchcondition(
			String contentpluginSearchcondition) {
		this.contentpluginSearchcondition = contentpluginSearchcondition;
	}
	public String toString(){
		return "contentpluginId="+contentpluginId+
				",contentpluginName="+contentpluginName+
				",contentpluginNodeid="+contentpluginNodeid+
				",contentpluginArticleid="+contentpluginArticleid+
				",contentpluginUserid="+contentpluginUserid+
				",contentpluginInsertdate="+contentpluginInsertdate+
				",contentpluginMust="+contentpluginMust+
				",contentpluginArbitrarily="+contentpluginArbitrarily+
				",contentpluginNot"+contentpluginNot+
				",contentpluginFromsource"+contentpluginFromsource+
				",contentpluginStarttime="+contentpluginStarttime+
				",contentpluginEndtime="+contentpluginEndtime+
				",strType="+strType;
				
				
	}
}