package com.database.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ContentPluginExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public ContentPluginExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andContentpluginIdIsNull() {
			addCriterion("contentplugin_id is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdIsNotNull() {
			addCriterion("contentplugin_id is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdEqualTo(Integer value) {
			addCriterion("contentplugin_id =", value, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdNotEqualTo(Integer value) {
			addCriterion("contentplugin_id <>", value, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdGreaterThan(Integer value) {
			addCriterion("contentplugin_id >", value, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_id >=", value, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdLessThan(Integer value) {
			addCriterion("contentplugin_id <", value, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdLessThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_id <=", value, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdIn(List<Integer> values) {
			addCriterion("contentplugin_id in", values, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdNotIn(List<Integer> values) {
			addCriterion("contentplugin_id not in", values, "contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdBetween(Integer value1, Integer value2) {
			addCriterion("contentplugin_id between", value1, value2,
					"contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_id not between", value1, value2,
					"contentpluginId");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameIsNull() {
			addCriterion("contentplugin_name is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameIsNotNull() {
			addCriterion("contentplugin_name is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameEqualTo(String value) {
			addCriterion("contentplugin_name =", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameNotEqualTo(String value) {
			addCriterion("contentplugin_name <>", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameGreaterThan(String value) {
			addCriterion("contentplugin_name >", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameGreaterThanOrEqualTo(String value) {
			addCriterion("contentplugin_name >=", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameLessThan(String value) {
			addCriterion("contentplugin_name <", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameLessThanOrEqualTo(String value) {
			addCriterion("contentplugin_name <=", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameLike(String value) {
			addCriterion("contentplugin_name like", value, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameNotLike(String value) {
			addCriterion("contentplugin_name not like", value,
					"contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameIn(List<String> values) {
			addCriterion("contentplugin_name in", values, "contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameNotIn(List<String> values) {
			addCriterion("contentplugin_name not in", values,
					"contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameBetween(String value1, String value2) {
			addCriterion("contentplugin_name between", value1, value2,
					"contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNameNotBetween(String value1,
				String value2) {
			addCriterion("contentplugin_name not between", value1, value2,
					"contentpluginName");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidIsNull() {
			addCriterion("contentplugin_nodeid is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidIsNotNull() {
			addCriterion("contentplugin_nodeid is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidEqualTo(Integer value) {
			addCriterion("contentplugin_nodeid =", value, "contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidNotEqualTo(Integer value) {
			addCriterion("contentplugin_nodeid <>", value,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidGreaterThan(Integer value) {
			addCriterion("contentplugin_nodeid >", value, "contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidGreaterThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_nodeid >=", value,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidLessThan(Integer value) {
			addCriterion("contentplugin_nodeid <", value, "contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidLessThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_nodeid <=", value,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidIn(List<Integer> values) {
			addCriterion("contentplugin_nodeid in", values,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidNotIn(List<Integer> values) {
			addCriterion("contentplugin_nodeid not in", values,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_nodeid between", value1, value2,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginNodeidNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_nodeid not between", value1, value2,
					"contentpluginNodeid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidIsNull() {
			addCriterion("contentplugin_articleid is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidIsNotNull() {
			addCriterion("contentplugin_articleid is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidEqualTo(Integer value) {
			addCriterion("contentplugin_articleid =", value,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidNotEqualTo(Integer value) {
			addCriterion("contentplugin_articleid <>", value,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidGreaterThan(Integer value) {
			addCriterion("contentplugin_articleid >", value,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_articleid >=", value,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidLessThan(Integer value) {
			addCriterion("contentplugin_articleid <", value,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidLessThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_articleid <=", value,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidIn(List<Integer> values) {
			addCriterion("contentplugin_articleid in", values,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidNotIn(List<Integer> values) {
			addCriterion("contentplugin_articleid not in", values,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_articleid between", value1, value2,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginArticleidNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_articleid not between", value1, value2,
					"contentpluginArticleid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridIsNull() {
			addCriterion("contentplugin_userid is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridIsNotNull() {
			addCriterion("contentplugin_userid is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridEqualTo(Integer value) {
			addCriterion("contentplugin_userid =", value, "contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridNotEqualTo(Integer value) {
			addCriterion("contentplugin_userid <>", value,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridGreaterThan(Integer value) {
			addCriterion("contentplugin_userid >", value, "contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_userid >=", value,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridLessThan(Integer value) {
			addCriterion("contentplugin_userid <", value, "contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridLessThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_userid <=", value,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridIn(List<Integer> values) {
			addCriterion("contentplugin_userid in", values,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridNotIn(List<Integer> values) {
			addCriterion("contentplugin_userid not in", values,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_userid between", value1, value2,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginUseridNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_userid not between", value1, value2,
					"contentpluginUserid");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateIsNull() {
			addCriterion("contentplugin_insertdate is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateIsNotNull() {
			addCriterion("contentplugin_insertdate is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_insertdate =", value,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateNotEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_insertdate <>", value,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateGreaterThan(Date value) {
			addCriterionForJDBCDate("contentplugin_insertdate >", value,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateGreaterThanOrEqualTo(
				Date value) {
			addCriterionForJDBCDate("contentplugin_insertdate >=", value,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateLessThan(Date value) {
			addCriterionForJDBCDate("contentplugin_insertdate <", value,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_insertdate <=", value,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_insertdate in", values,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateNotIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_insertdate not in", values,
					"contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_insertdate between", value1,
					value2, "contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginInsertdateNotBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_insertdate not between",
					value1, value2, "contentpluginInsertdate");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustIsNull() {
			addCriterion("contentplugin_must is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustIsNotNull() {
			addCriterion("contentplugin_must is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustEqualTo(String value) {
			addCriterion("contentplugin_must =", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustNotEqualTo(String value) {
			addCriterion("contentplugin_must <>", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustGreaterThan(String value) {
			addCriterion("contentplugin_must >", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustGreaterThanOrEqualTo(String value) {
			addCriterion("contentplugin_must >=", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustLessThan(String value) {
			addCriterion("contentplugin_must <", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustLessThanOrEqualTo(String value) {
			addCriterion("contentplugin_must <=", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustLike(String value) {
			addCriterion("contentplugin_must like", value, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustNotLike(String value) {
			addCriterion("contentplugin_must not like", value,
					"contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustIn(List<String> values) {
			addCriterion("contentplugin_must in", values, "contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustNotIn(List<String> values) {
			addCriterion("contentplugin_must not in", values,
					"contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustBetween(String value1, String value2) {
			addCriterion("contentplugin_must between", value1, value2,
					"contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginMustNotBetween(String value1,
				String value2) {
			addCriterion("contentplugin_must not between", value1, value2,
					"contentpluginMust");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyIsNull() {
			addCriterion("contentplugin_arbitrarily is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyIsNotNull() {
			addCriterion("contentplugin_arbitrarily is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyEqualTo(String value) {
			addCriterion("contentplugin_arbitrarily =", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyNotEqualTo(String value) {
			addCriterion("contentplugin_arbitrarily <>", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyGreaterThan(String value) {
			addCriterion("contentplugin_arbitrarily >", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyGreaterThanOrEqualTo(
				String value) {
			addCriterion("contentplugin_arbitrarily >=", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyLessThan(String value) {
			addCriterion("contentplugin_arbitrarily <", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyLessThanOrEqualTo(
				String value) {
			addCriterion("contentplugin_arbitrarily <=", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyLike(String value) {
			addCriterion("contentplugin_arbitrarily like", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyNotLike(String value) {
			addCriterion("contentplugin_arbitrarily not like", value,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyIn(List<String> values) {
			addCriterion("contentplugin_arbitrarily in", values,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyNotIn(List<String> values) {
			addCriterion("contentplugin_arbitrarily not in", values,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyBetween(String value1,
				String value2) {
			addCriterion("contentplugin_arbitrarily between", value1, value2,
					"contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginArbitrarilyNotBetween(String value1,
				String value2) {
			addCriterion("contentplugin_arbitrarily not between", value1,
					value2, "contentpluginArbitrarily");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotIsNull() {
			addCriterion("contentplugin_not is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotIsNotNull() {
			addCriterion("contentplugin_not is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotEqualTo(String value) {
			addCriterion("contentplugin_not =", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotNotEqualTo(String value) {
			addCriterion("contentplugin_not <>", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotGreaterThan(String value) {
			addCriterion("contentplugin_not >", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotGreaterThanOrEqualTo(String value) {
			addCriterion("contentplugin_not >=", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotLessThan(String value) {
			addCriterion("contentplugin_not <", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotLessThanOrEqualTo(String value) {
			addCriterion("contentplugin_not <=", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotLike(String value) {
			addCriterion("contentplugin_not like", value, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotNotLike(String value) {
			addCriterion("contentplugin_not not like", value,
					"contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotIn(List<String> values) {
			addCriterion("contentplugin_not in", values, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotNotIn(List<String> values) {
			addCriterion("contentplugin_not not in", values, "contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotBetween(String value1, String value2) {
			addCriterion("contentplugin_not between", value1, value2,
					"contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginNotNotBetween(String value1,
				String value2) {
			addCriterion("contentplugin_not not between", value1, value2,
					"contentpluginNot");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceIsNull() {
			addCriterion("contentplugin_searchsource is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceIsNotNull() {
			addCriterion("contentplugin_searchsource is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceEqualTo(Integer value) {
			addCriterion("contentplugin_searchsource =", value,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceNotEqualTo(Integer value) {
			addCriterion("contentplugin_searchsource <>", value,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceGreaterThan(Integer value) {
			addCriterion("contentplugin_searchsource >", value,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_searchsource >=", value,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceLessThan(Integer value) {
			addCriterion("contentplugin_searchsource <", value,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceLessThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_searchsource <=", value,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceIn(List<Integer> values) {
			addCriterion("contentplugin_searchsource in", values,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceNotIn(List<Integer> values) {
			addCriterion("contentplugin_searchsource not in", values,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_searchsource between", value1, value2,
					"contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSearchsourceNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_searchsource not between", value1,
					value2, "contentpluginSearchsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortIsNull() {
			addCriterion("contentplugin_sort is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortIsNotNull() {
			addCriterion("contentplugin_sort is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortEqualTo(Integer value) {
			addCriterion("contentplugin_sort =", value, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortNotEqualTo(Integer value) {
			addCriterion("contentplugin_sort <>", value, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortGreaterThan(Integer value) {
			addCriterion("contentplugin_sort >", value, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_sort >=", value, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortLessThan(Integer value) {
			addCriterion("contentplugin_sort <", value, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortLessThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_sort <=", value, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortIn(List<Integer> values) {
			addCriterion("contentplugin_sort in", values, "contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortNotIn(List<Integer> values) {
			addCriterion("contentplugin_sort not in", values,
					"contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_sort between", value1, value2,
					"contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginSortNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_sort not between", value1, value2,
					"contentpluginSort");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceIsNull() {
			addCriterion("contentplugin_fromsource is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceIsNotNull() {
			addCriterion("contentplugin_fromsource is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceEqualTo(String value) {
			addCriterion("contentplugin_fromsource =", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceNotEqualTo(String value) {
			addCriterion("contentplugin_fromsource <>", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceGreaterThan(String value) {
			addCriterion("contentplugin_fromsource >", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceGreaterThanOrEqualTo(
				String value) {
			addCriterion("contentplugin_fromsource >=", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceLessThan(String value) {
			addCriterion("contentplugin_fromsource <", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceLessThanOrEqualTo(String value) {
			addCriterion("contentplugin_fromsource <=", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceLike(String value) {
			addCriterion("contentplugin_fromsource like", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceNotLike(String value) {
			addCriterion("contentplugin_fromsource not like", value,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceIn(List<String> values) {
			addCriterion("contentplugin_fromsource in", values,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceNotIn(List<String> values) {
			addCriterion("contentplugin_fromsource not in", values,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceBetween(String value1,
				String value2) {
			addCriterion("contentplugin_fromsource between", value1, value2,
					"contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginFromsourceNotBetween(String value1,
				String value2) {
			addCriterion("contentplugin_fromsource not between", value1,
					value2, "contentpluginFromsource");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeIsNull() {
			addCriterion("contentplugin_pagesize is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeIsNotNull() {
			addCriterion("contentplugin_pagesize is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeEqualTo(Integer value) {
			addCriterion("contentplugin_pagesize =", value,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeNotEqualTo(Integer value) {
			addCriterion("contentplugin_pagesize <>", value,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeGreaterThan(Integer value) {
			addCriterion("contentplugin_pagesize >", value,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_pagesize >=", value,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeLessThan(Integer value) {
			addCriterion("contentplugin_pagesize <", value,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeLessThanOrEqualTo(Integer value) {
			addCriterion("contentplugin_pagesize <=", value,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeIn(List<Integer> values) {
			addCriterion("contentplugin_pagesize in", values,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeNotIn(List<Integer> values) {
			addCriterion("contentplugin_pagesize not in", values,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_pagesize between", value1, value2,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginPagesizeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_pagesize not between", value1, value2,
					"contentpluginPagesize");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeIsNull() {
			addCriterion("contentplugin_starttime is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeIsNotNull() {
			addCriterion("contentplugin_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_starttime =", value,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_starttime <>", value,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeGreaterThan(Date value) {
			addCriterionForJDBCDate("contentplugin_starttime >", value,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_starttime >=", value,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeLessThan(Date value) {
			addCriterionForJDBCDate("contentplugin_starttime <", value,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_starttime <=", value,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_starttime in", values,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_starttime not in", values,
					"contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_starttime between", value1,
					value2, "contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginStarttimeNotBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_starttime not between",
					value1, value2, "contentpluginStarttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeIsNull() {
			addCriterion("contentplugin_endtime is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeIsNotNull() {
			addCriterion("contentplugin_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_endtime =", value,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_endtime <>", value,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeGreaterThan(Date value) {
			addCriterionForJDBCDate("contentplugin_endtime >", value,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_endtime >=", value,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeLessThan(Date value) {
			addCriterionForJDBCDate("contentplugin_endtime <", value,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_endtime <=", value,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_endtime in", values,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_endtime not in", values,
					"contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("contentplugin_endtime between", value1,
					value2, "contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginEndtimeNotBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_endtime not between",
					value1, value2, "contentpluginEndtime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagIsNull() {
			addCriterion("contentplugin_repeatflag is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagIsNotNull() {
			addCriterion("contentplugin_repeatflag is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagEqualTo(Integer value) {
			addCriterion("contentplugin_repeatflag =", value,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagNotEqualTo(Integer value) {
			addCriterion("contentplugin_repeatflag <>", value,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagGreaterThan(Integer value) {
			addCriterion("contentplugin_repeatflag >", value,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_repeatflag >=", value,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagLessThan(Integer value) {
			addCriterion("contentplugin_repeatflag <", value,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagLessThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_repeatflag <=", value,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagIn(List<Integer> values) {
			addCriterion("contentplugin_repeatflag in", values,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagNotIn(List<Integer> values) {
			addCriterion("contentplugin_repeatflag not in", values,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_repeatflag between", value1, value2,
					"contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeatflagNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_repeatflag not between", value1,
					value2, "contentpluginRepeatflag");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeIsNull() {
			addCriterion("contentplugin_repeattime is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeIsNotNull() {
			addCriterion("contentplugin_repeattime is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeEqualTo(Integer value) {
			addCriterion("contentplugin_repeattime =", value,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeNotEqualTo(Integer value) {
			addCriterion("contentplugin_repeattime <>", value,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeGreaterThan(Integer value) {
			addCriterion("contentplugin_repeattime >", value,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_repeattime >=", value,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeLessThan(Integer value) {
			addCriterion("contentplugin_repeattime <", value,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeLessThanOrEqualTo(
				Integer value) {
			addCriterion("contentplugin_repeattime <=", value,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeIn(List<Integer> values) {
			addCriterion("contentplugin_repeattime in", values,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeNotIn(List<Integer> values) {
			addCriterion("contentplugin_repeattime not in", values,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_repeattime between", value1, value2,
					"contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginRepeattimeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("contentplugin_repeattime not between", value1,
					value2, "contentpluginRepeattime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeIsNull() {
			addCriterion("contentplugin_updatetime is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeIsNotNull() {
			addCriterion("contentplugin_updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_updatetime =", value,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_updatetime <>", value,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeGreaterThan(Date value) {
			addCriterionForJDBCDate("contentplugin_updatetime >", value,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeGreaterThanOrEqualTo(
				Date value) {
			addCriterionForJDBCDate("contentplugin_updatetime >=", value,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeLessThan(Date value) {
			addCriterionForJDBCDate("contentplugin_updatetime <", value,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("contentplugin_updatetime <=", value,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_updatetime in", values,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("contentplugin_updatetime not in", values,
					"contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_updatetime between", value1,
					value2, "contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginUpdatetimeNotBetween(Date value1,
				Date value2) {
			addCriterionForJDBCDate("contentplugin_updatetime not between",
					value1, value2, "contentpluginUpdatetime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeIsNull() {
			addCriterion("contentplugin_inserttime is null");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeIsNotNull() {
			addCriterion("contentplugin_inserttime is not null");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeEqualTo(Date value) {
			addCriterion("contentplugin_inserttime =", value,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeNotEqualTo(Date value) {
			addCriterion("contentplugin_inserttime <>", value,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeGreaterThan(Date value) {
			addCriterion("contentplugin_inserttime >", value,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeGreaterThanOrEqualTo(
				Date value) {
			addCriterion("contentplugin_inserttime >=", value,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeLessThan(Date value) {
			addCriterion("contentplugin_inserttime <", value,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeLessThanOrEqualTo(Date value) {
			addCriterion("contentplugin_inserttime <=", value,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeIn(List<Date> values) {
			addCriterion("contentplugin_inserttime in", values,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeNotIn(List<Date> values) {
			addCriterion("contentplugin_inserttime not in", values,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeBetween(Date value1,
				Date value2) {
			addCriterion("contentplugin_inserttime between", value1, value2,
					"contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andContentpluginInserttimeNotBetween(Date value1,
				Date value2) {
			addCriterion("contentplugin_inserttime not between", value1,
					value2, "contentpluginInserttime");
			return (Criteria) this;
		}

		public Criteria andStrTypeIsNull() {
			addCriterion("str_type is null");
			return (Criteria) this;
		}

		public Criteria andStrTypeIsNotNull() {
			addCriterion("str_type is not null");
			return (Criteria) this;
		}

		public Criteria andStrTypeEqualTo(String value) {
			addCriterion("str_type =", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeNotEqualTo(String value) {
			addCriterion("str_type <>", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeGreaterThan(String value) {
			addCriterion("str_type >", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeGreaterThanOrEqualTo(String value) {
			addCriterion("str_type >=", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeLessThan(String value) {
			addCriterion("str_type <", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeLessThanOrEqualTo(String value) {
			addCriterion("str_type <=", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeLike(String value) {
			addCriterion("str_type like", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeNotLike(String value) {
			addCriterion("str_type not like", value, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeIn(List<String> values) {
			addCriterion("str_type in", values, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeNotIn(List<String> values) {
			addCriterion("str_type not in", values, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeBetween(String value1, String value2) {
			addCriterion("str_type between", value1, value2, "strType");
			return (Criteria) this;
		}

		public Criteria andStrTypeNotBetween(String value1, String value2) {
			addCriterion("str_type not between", value1, value2, "strType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table know_contentplugin
	 * @mbggenerated  Sun Sep 06 14:10:02 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table know_contentplugin
     *
     * @mbggenerated do_not_delete_during_merge Thu May 21 09:57:48 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}