package com.database.bean;

import java.util.Date;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.content_id
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.content_name
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private String contentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.user_id
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.insert_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.update_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.pass_type
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private String passType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.pass_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Date passTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.pass_user
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Integer passUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.keyword
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.file_index
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Integer fileIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column know_content.savestatus
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    private Integer savestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.content_id
     *
     * @return the value of know_content.content_id
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.content_id
     *
     * @param contentId the value for know_content.content_id
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.content_name
     *
     * @return the value of know_content.content_name
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public String getContentName() {
        return contentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.content_name
     *
     * @param contentName the value for know_content.content_name
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setContentName(String contentName) {
        this.contentName = contentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.user_id
     *
     * @return the value of know_content.user_id
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.user_id
     *
     * @param userId the value for know_content.user_id
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.insert_time
     *
     * @return the value of know_content.insert_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.insert_time
     *
     * @param insertTime the value for know_content.insert_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.update_time
     *
     * @return the value of know_content.update_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.update_time
     *
     * @param updateTime the value for know_content.update_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.pass_type
     *
     * @return the value of know_content.pass_type
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public String getPassType() {
        return passType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.pass_type
     *
     * @param passType the value for know_content.pass_type
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setPassType(String passType) {
        this.passType = passType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.pass_time
     *
     * @return the value of know_content.pass_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Date getPassTime() {
        return passTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.pass_time
     *
     * @param passTime the value for know_content.pass_time
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setPassTime(Date passTime) {
        this.passTime = passTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.pass_user
     *
     * @return the value of know_content.pass_user
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Integer getPassUser() {
        return passUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.pass_user
     *
     * @param passUser the value for know_content.pass_user
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setPassUser(Integer passUser) {
        this.passUser = passUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.keyword
     *
     * @return the value of know_content.keyword
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.keyword
     *
     * @param keyword the value for know_content.keyword
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.file_index
     *
     * @return the value of know_content.file_index
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Integer getFileIndex() {
        return fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.file_index
     *
     * @param fileIndex the value for know_content.file_index
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setFileIndex(Integer fileIndex) {
        this.fileIndex = fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column know_content.savestatus
     *
     * @return the value of know_content.savestatus
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public Integer getSavestatus() {
        return savestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column know_content.savestatus
     *
     * @param savestatus the value for know_content.savestatus
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    public void setSavestatus(Integer savestatus) {
        this.savestatus = savestatus;
    }
}