package com.database.bean;

import java.util.Date;

public class Crawl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.crawl_id
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Integer crawlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.website_id
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Integer websiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.crawl_title
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private String crawlTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.crawl_brief
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private String crawlBrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.crawl_views
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Integer crawlViews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.web_name
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private String webName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.url
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.file_index
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Boolean fileIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.news_time
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Date newsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.crawl_time
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl.task
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    private Byte task;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.crawl_id
     *
     * @return the value of ptf_crawl.crawl_id
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Integer getCrawlId() {
        return crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.crawl_id
     *
     * @param crawlId the value for ptf_crawl.crawl_id
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.website_id
     *
     * @return the value of ptf_crawl.website_id
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.website_id
     *
     * @param websiteId the value for ptf_crawl.website_id
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.crawl_title
     *
     * @return the value of ptf_crawl.crawl_title
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public String getCrawlTitle() {
        return crawlTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.crawl_title
     *
     * @param crawlTitle the value for ptf_crawl.crawl_title
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setCrawlTitle(String crawlTitle) {
        this.crawlTitle = crawlTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.crawl_brief
     *
     * @return the value of ptf_crawl.crawl_brief
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public String getCrawlBrief() {
        return crawlBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.crawl_brief
     *
     * @param crawlBrief the value for ptf_crawl.crawl_brief
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setCrawlBrief(String crawlBrief) {
        this.crawlBrief = crawlBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.crawl_views
     *
     * @return the value of ptf_crawl.crawl_views
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Integer getCrawlViews() {
        return crawlViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.crawl_views
     *
     * @param crawlViews the value for ptf_crawl.crawl_views
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setCrawlViews(Integer crawlViews) {
        this.crawlViews = crawlViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.web_name
     *
     * @return the value of ptf_crawl.web_name
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public String getWebName() {
        return webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.web_name
     *
     * @param webName the value for ptf_crawl.web_name
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setWebName(String webName) {
        this.webName = webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.url
     *
     * @return the value of ptf_crawl.url
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.url
     *
     * @param url the value for ptf_crawl.url
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.file_index
     *
     * @return the value of ptf_crawl.file_index
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Boolean getFileIndex() {
        return fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.file_index
     *
     * @param fileIndex the value for ptf_crawl.file_index
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setFileIndex(Boolean fileIndex) {
        this.fileIndex = fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.news_time
     *
     * @return the value of ptf_crawl.news_time
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Date getNewsTime() {
        return newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.news_time
     *
     * @param newsTime the value for ptf_crawl.news_time
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setNewsTime(Date newsTime) {
        this.newsTime = newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.crawl_time
     *
     * @return the value of ptf_crawl.crawl_time
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.crawl_time
     *
     * @param crawlTime the value for ptf_crawl.crawl_time
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl.task
     *
     * @return the value of ptf_crawl.task
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public Byte getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl.task
     *
     * @param task the value for ptf_crawl.task
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    public void setTask(Byte task) {
        this.task = task;
    }
}