package com.database.bean;

import java.util.Date;

public class Industry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.id
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.pid
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.ind_code
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private String indCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.name
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.level
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.end
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Byte end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.code
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.effective_date
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.expiry_date
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ind_industry.show_index
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    private Integer showIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.id
     *
     * @return the value of ind_industry.id
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.id
     *
     * @param id the value for ind_industry.id
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.pid
     *
     * @return the value of ind_industry.pid
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.pid
     *
     * @param pid the value for ind_industry.pid
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.ind_code
     *
     * @return the value of ind_industry.ind_code
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public String getIndCode() {
        return indCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.ind_code
     *
     * @param indCode the value for ind_industry.ind_code
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setIndCode(String indCode) {
        this.indCode = indCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.name
     *
     * @return the value of ind_industry.name
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.name
     *
     * @param name the value for ind_industry.name
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.level
     *
     * @return the value of ind_industry.level
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.level
     *
     * @param level the value for ind_industry.level
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.end
     *
     * @return the value of ind_industry.end
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Byte getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.end
     *
     * @param end the value for ind_industry.end
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setEnd(Byte end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.code
     *
     * @return the value of ind_industry.code
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.code
     *
     * @param code the value for ind_industry.code
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.effective_date
     *
     * @return the value of ind_industry.effective_date
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.effective_date
     *
     * @param effectiveDate the value for ind_industry.effective_date
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.expiry_date
     *
     * @return the value of ind_industry.expiry_date
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.expiry_date
     *
     * @param expiryDate the value for ind_industry.expiry_date
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ind_industry.show_index
     *
     * @return the value of ind_industry.show_index
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public Integer getShowIndex() {
        return showIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ind_industry.show_index
     *
     * @param showIndex the value for ind_industry.show_index
     *
     * @mbggenerated Fri Apr 10 11:49:54 CST 2015
     */
    public void setShowIndex(Integer showIndex) {
        this.showIndex = showIndex;
    }
}