package com.database.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class MyModuleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public MyModuleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userid is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userid is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("userid =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("userid <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("userid >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("userid >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("userid <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("userid <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("userid in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("userid not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("userid between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("userid not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andStationIsNull() {
			addCriterion("station is null");
			return (Criteria) this;
		}

		public Criteria andStationIsNotNull() {
			addCriterion("station is not null");
			return (Criteria) this;
		}

		public Criteria andStationEqualTo(String value) {
			addCriterion("station =", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationNotEqualTo(String value) {
			addCriterion("station <>", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationGreaterThan(String value) {
			addCriterion("station >", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationGreaterThanOrEqualTo(String value) {
			addCriterion("station >=", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationLessThan(String value) {
			addCriterion("station <", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationLessThanOrEqualTo(String value) {
			addCriterion("station <=", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationLike(String value) {
			addCriterion("station like", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationNotLike(String value) {
			addCriterion("station not like", value, "station");
			return (Criteria) this;
		}

		public Criteria andStationIn(List<String> values) {
			addCriterion("station in", values, "station");
			return (Criteria) this;
		}

		public Criteria andStationNotIn(List<String> values) {
			addCriterion("station not in", values, "station");
			return (Criteria) this;
		}

		public Criteria andStationBetween(String value1, String value2) {
			addCriterion("station between", value1, value2, "station");
			return (Criteria) this;
		}

		public Criteria andStationNotBetween(String value1, String value2) {
			addCriterion("station not between", value1, value2, "station");
			return (Criteria) this;
		}

		public Criteria andResponsibilityIsNull() {
			addCriterion("responsibility is null");
			return (Criteria) this;
		}

		public Criteria andResponsibilityIsNotNull() {
			addCriterion("responsibility is not null");
			return (Criteria) this;
		}

		public Criteria andResponsibilityEqualTo(String value) {
			addCriterion("responsibility =", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityNotEqualTo(String value) {
			addCriterion("responsibility <>", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityGreaterThan(String value) {
			addCriterion("responsibility >", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityGreaterThanOrEqualTo(String value) {
			addCriterion("responsibility >=", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityLessThan(String value) {
			addCriterion("responsibility <", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityLessThanOrEqualTo(String value) {
			addCriterion("responsibility <=", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityLike(String value) {
			addCriterion("responsibility like", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityNotLike(String value) {
			addCriterion("responsibility not like", value, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityIn(List<String> values) {
			addCriterion("responsibility in", values, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityNotIn(List<String> values) {
			addCriterion("responsibility not in", values, "responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityBetween(String value1, String value2) {
			addCriterion("responsibility between", value1, value2,
					"responsibility");
			return (Criteria) this;
		}

		public Criteria andResponsibilityNotBetween(String value1, String value2) {
			addCriterion("responsibility not between", value1, value2,
					"responsibility");
			return (Criteria) this;
		}

		public Criteria andInterestIsNull() {
			addCriterion("interest is null");
			return (Criteria) this;
		}

		public Criteria andInterestIsNotNull() {
			addCriterion("interest is not null");
			return (Criteria) this;
		}

		public Criteria andInterestEqualTo(String value) {
			addCriterion("interest =", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestNotEqualTo(String value) {
			addCriterion("interest <>", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestGreaterThan(String value) {
			addCriterion("interest >", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestGreaterThanOrEqualTo(String value) {
			addCriterion("interest >=", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestLessThan(String value) {
			addCriterion("interest <", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestLessThanOrEqualTo(String value) {
			addCriterion("interest <=", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestLike(String value) {
			addCriterion("interest like", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestNotLike(String value) {
			addCriterion("interest not like", value, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestIn(List<String> values) {
			addCriterion("interest in", values, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestNotIn(List<String> values) {
			addCriterion("interest not in", values, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestBetween(String value1, String value2) {
			addCriterion("interest between", value1, value2, "interest");
			return (Criteria) this;
		}

		public Criteria andInterestNotBetween(String value1, String value2) {
			addCriterion("interest not between", value1, value2, "interest");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createdate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createdate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createdate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createdate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createdate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createdate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createdate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createdate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createdate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createdate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("province is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("province is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("province =", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("province <>", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("province >", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("province >=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("province <", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("province <=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("province like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("province not like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceIn(List<String> values) {
			addCriterion("province in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotIn(List<String> values) {
			addCriterion("province not in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("province between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("province not between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andPhoneflagIsNull() {
			addCriterion("phoneFlag is null");
			return (Criteria) this;
		}

		public Criteria andPhoneflagIsNotNull() {
			addCriterion("phoneFlag is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneflagEqualTo(Integer value) {
			addCriterion("phoneFlag =", value, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagNotEqualTo(Integer value) {
			addCriterion("phoneFlag <>", value, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagGreaterThan(Integer value) {
			addCriterion("phoneFlag >", value, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("phoneFlag >=", value, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagLessThan(Integer value) {
			addCriterion("phoneFlag <", value, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagLessThanOrEqualTo(Integer value) {
			addCriterion("phoneFlag <=", value, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagIn(List<Integer> values) {
			addCriterion("phoneFlag in", values, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagNotIn(List<Integer> values) {
			addCriterion("phoneFlag not in", values, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagBetween(Integer value1, Integer value2) {
			addCriterion("phoneFlag between", value1, value2, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andPhoneflagNotBetween(Integer value1, Integer value2) {
			addCriterion("phoneFlag not between", value1, value2, "phoneflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagIsNull() {
			addCriterion("emailFlag is null");
			return (Criteria) this;
		}

		public Criteria andEmailflagIsNotNull() {
			addCriterion("emailFlag is not null");
			return (Criteria) this;
		}

		public Criteria andEmailflagEqualTo(Integer value) {
			addCriterion("emailFlag =", value, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagNotEqualTo(Integer value) {
			addCriterion("emailFlag <>", value, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagGreaterThan(Integer value) {
			addCriterion("emailFlag >", value, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagGreaterThanOrEqualTo(Integer value) {
			addCriterion("emailFlag >=", value, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagLessThan(Integer value) {
			addCriterion("emailFlag <", value, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagLessThanOrEqualTo(Integer value) {
			addCriterion("emailFlag <=", value, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagIn(List<Integer> values) {
			addCriterion("emailFlag in", values, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagNotIn(List<Integer> values) {
			addCriterion("emailFlag not in", values, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagBetween(Integer value1, Integer value2) {
			addCriterion("emailFlag between", value1, value2, "emailflag");
			return (Criteria) this;
		}

		public Criteria andEmailflagNotBetween(Integer value1, Integer value2) {
			addCriterion("emailFlag not between", value1, value2, "emailflag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mymodule
	 * @mbggenerated  Thu Aug 06 09:25:13 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mymodule
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 04 14:23:37 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}