package com.database.bean;

public class NewsPic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_pic.id
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_pic.name
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_pic.path
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	private String path;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_pic.id
	 * @return  the value of news_pic.id
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_pic.id
	 * @param id  the value for news_pic.id
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_pic.name
	 * @return  the value of news_pic.name
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_pic.name
	 * @param name  the value for news_pic.name
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_pic.path
	 * @return  the value of news_pic.path
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_pic.path
	 * @param path  the value for news_pic.path
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	public void setPath(String path) {
		this.path = path;
	}
}