package com.database.bean;

import java.util.Date;

public class NewsStopWord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_stop_word.id
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_stop_word.stop_word
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	private String stopWord;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_stop_word.do_id
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	private Integer doId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_stop_word.insert_time
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	private Date insertTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_stop_word.id
	 * @return  the value of news_stop_word.id
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_stop_word.id
	 * @param id  the value for news_stop_word.id
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_stop_word.stop_word
	 * @return  the value of news_stop_word.stop_word
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public String getStopWord() {
		return stopWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_stop_word.stop_word
	 * @param stopWord  the value for news_stop_word.stop_word
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public void setStopWord(String stopWord) {
		this.stopWord = stopWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_stop_word.do_id
	 * @return  the value of news_stop_word.do_id
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public Integer getDoId() {
		return doId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_stop_word.do_id
	 * @param doId  the value for news_stop_word.do_id
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public void setDoId(Integer doId) {
		this.doId = doId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_stop_word.insert_time
	 * @return  the value of news_stop_word.insert_time
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_stop_word.insert_time
	 * @param insertTime  the value for news_stop_word.insert_time
	 * @mbggenerated  Thu Feb 18 09:07:19 GMT+08:00 2016
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
}