package com.database.bean;

import java.util.Date;

public class PluginUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin_user.plugin_user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Integer pluginUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin_user.plugin_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Integer pluginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin_user.user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin_user.my_plugin_name
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private String myPluginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin_user.insert_time
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Date insertTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin_user.plugin_user_id
	 * @return  the value of know_plugin_user.plugin_user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Integer getPluginUserId() {
		return pluginUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin_user.plugin_user_id
	 * @param pluginUserId  the value for know_plugin_user.plugin_user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginUserId(Integer pluginUserId) {
		this.pluginUserId = pluginUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin_user.plugin_id
	 * @return  the value of know_plugin_user.plugin_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Integer getPluginId() {
		return pluginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin_user.plugin_id
	 * @param pluginId  the value for know_plugin_user.plugin_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginId(Integer pluginId) {
		this.pluginId = pluginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin_user.user_id
	 * @return  the value of know_plugin_user.user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin_user.user_id
	 * @param userId  the value for know_plugin_user.user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin_user.my_plugin_name
	 * @return  the value of know_plugin_user.my_plugin_name
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public String getMyPluginName() {
		return myPluginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin_user.my_plugin_name
	 * @param myPluginName  the value for know_plugin_user.my_plugin_name
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setMyPluginName(String myPluginName) {
		this.myPluginName = myPluginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin_user.insert_time
	 * @return  the value of know_plugin_user.insert_time
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin_user.insert_time
	 * @param insertTime  the value for know_plugin_user.insert_time
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
}