package com.database.bean;

import java.util.Date;

public class Plugin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.plugin_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Integer pluginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.plugin_name
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private String pluginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.plugin_intro
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private String pluginIntro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.plugin_index
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private String pluginIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.plugin_params
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private String pluginParams;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.plugin_note
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private String pluginNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.insert_time
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column know_plugin.file_index
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	private Integer fileIndex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.plugin_id
	 * @return  the value of know_plugin.plugin_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Integer getPluginId() {
		return pluginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.plugin_id
	 * @param pluginId  the value for know_plugin.plugin_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginId(Integer pluginId) {
		this.pluginId = pluginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.plugin_name
	 * @return  the value of know_plugin.plugin_name
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public String getPluginName() {
		return pluginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.plugin_name
	 * @param pluginName  the value for know_plugin.plugin_name
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginName(String pluginName) {
		this.pluginName = pluginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.plugin_intro
	 * @return  the value of know_plugin.plugin_intro
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public String getPluginIntro() {
		return pluginIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.plugin_intro
	 * @param pluginIntro  the value for know_plugin.plugin_intro
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginIntro(String pluginIntro) {
		this.pluginIntro = pluginIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.user_id
	 * @return  the value of know_plugin.user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.user_id
	 * @param userId  the value for know_plugin.user_id
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.plugin_index
	 * @return  the value of know_plugin.plugin_index
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public String getPluginIndex() {
		return pluginIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.plugin_index
	 * @param pluginIndex  the value for know_plugin.plugin_index
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginIndex(String pluginIndex) {
		this.pluginIndex = pluginIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.plugin_params
	 * @return  the value of know_plugin.plugin_params
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public String getPluginParams() {
		return pluginParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.plugin_params
	 * @param pluginParams  the value for know_plugin.plugin_params
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginParams(String pluginParams) {
		this.pluginParams = pluginParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.plugin_note
	 * @return  the value of know_plugin.plugin_note
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public String getPluginNote() {
		return pluginNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.plugin_note
	 * @param pluginNote  the value for know_plugin.plugin_note
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setPluginNote(String pluginNote) {
		this.pluginNote = pluginNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.insert_time
	 * @return  the value of know_plugin.insert_time
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.insert_time
	 * @param insertTime  the value for know_plugin.insert_time
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column know_plugin.file_index
	 * @return  the value of know_plugin.file_index
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public Integer getFileIndex() {
		return fileIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column know_plugin.file_index
	 * @param fileIndex  the value for know_plugin.file_index
	 * @mbggenerated  Fri Apr 17 10:14:38 CST 2015
	 */
	public void setFileIndex(Integer fileIndex) {
		this.fileIndex = fileIndex;
	}
}