package com.database.bean;

import java.util.ArrayList;
import java.util.List;

public class UserOtherInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public UserOtherInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdEqualTo(Integer value) {
			addCriterion("company_id =", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotEqualTo(Integer value) {
			addCriterion("company_id <>", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThan(Integer value) {
			addCriterion("company_id >", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_id >=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThan(Integer value) {
			addCriterion("company_id <", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_id <=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIn(List<Integer> values) {
			addCriterion("company_id in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotIn(List<Integer> values) {
			addCriterion("company_id not in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoIsNull() {
			addCriterion("company_info is null");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoIsNotNull() {
			addCriterion("company_info is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoEqualTo(String value) {
			addCriterion("company_info =", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoNotEqualTo(String value) {
			addCriterion("company_info <>", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoGreaterThan(String value) {
			addCriterion("company_info >", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoGreaterThanOrEqualTo(String value) {
			addCriterion("company_info >=", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoLessThan(String value) {
			addCriterion("company_info <", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoLessThanOrEqualTo(String value) {
			addCriterion("company_info <=", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoLike(String value) {
			addCriterion("company_info like", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoNotLike(String value) {
			addCriterion("company_info not like", value, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoIn(List<String> values) {
			addCriterion("company_info in", values, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoNotIn(List<String> values) {
			addCriterion("company_info not in", values, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoBetween(String value1, String value2) {
			addCriterion("company_info between", value1, value2, "companyInfo");
			return (Criteria) this;
		}

		public Criteria andCompanyInfoNotBetween(String value1, String value2) {
			addCriterion("company_info not between", value1, value2,
					"companyInfo");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeIsNull() {
			addCriterion("company_type is null");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeIsNotNull() {
			addCriterion("company_type is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeEqualTo(Integer value) {
			addCriterion("company_type =", value, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeNotEqualTo(Integer value) {
			addCriterion("company_type <>", value, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeGreaterThan(Integer value) {
			addCriterion("company_type >", value, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_type >=", value, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeLessThan(Integer value) {
			addCriterion("company_type <", value, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeLessThanOrEqualTo(Integer value) {
			addCriterion("company_type <=", value, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeIn(List<Integer> values) {
			addCriterion("company_type in", values, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeNotIn(List<Integer> values) {
			addCriterion("company_type not in", values, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeBetween(Integer value1, Integer value2) {
			addCriterion("company_type between", value1, value2, "companyType");
			return (Criteria) this;
		}

		public Criteria andCompanyTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("company_type not between", value1, value2,
					"companyType");
			return (Criteria) this;
		}

		public Criteria andUserEditIsNull() {
			addCriterion("user_edit is null");
			return (Criteria) this;
		}

		public Criteria andUserEditIsNotNull() {
			addCriterion("user_edit is not null");
			return (Criteria) this;
		}

		public Criteria andUserEditEqualTo(String value) {
			addCriterion("user_edit =", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditNotEqualTo(String value) {
			addCriterion("user_edit <>", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditGreaterThan(String value) {
			addCriterion("user_edit >", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditGreaterThanOrEqualTo(String value) {
			addCriterion("user_edit >=", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditLessThan(String value) {
			addCriterion("user_edit <", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditLessThanOrEqualTo(String value) {
			addCriterion("user_edit <=", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditLike(String value) {
			addCriterion("user_edit like", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditNotLike(String value) {
			addCriterion("user_edit not like", value, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditIn(List<String> values) {
			addCriterion("user_edit in", values, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditNotIn(List<String> values) {
			addCriterion("user_edit not in", values, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditBetween(String value1, String value2) {
			addCriterion("user_edit between", value1, value2, "userEdit");
			return (Criteria) this;
		}

		public Criteria andUserEditNotBetween(String value1, String value2) {
			addCriterion("user_edit not between", value1, value2, "userEdit");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_other_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 07 16:23:40 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}