package com.database.bean;

public class WordLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_label.id
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_label.name
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_label.count
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_label.id
     *
     * @return the value of word_label.id
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_label.id
     *
     * @param id the value for word_label.id
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_label.name
     *
     * @return the value of word_label.name
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_label.name
     *
     * @param name the value for word_label.name
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_label.count
     *
     * @return the value of word_label.count
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_label.count
     *
     * @param count the value for word_label.count
     *
     * @mbggenerated Mon Sep 14 17:19:34 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}