package com.database.bean;

import java.util.Date;

public class WordShoppingCart {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.cart_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private Integer cartId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.user_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.resoure_type
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private String resoureType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.journal_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private Integer journalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.article_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private Integer articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.pay_flag
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private Integer payFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column word_shopping_cart.create_time
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.cart_id
	 * @return  the value of word_shopping_cart.cart_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public Integer getCartId() {
		return cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.cart_id
	 * @param cartId  the value for word_shopping_cart.cart_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.user_id
	 * @return  the value of word_shopping_cart.user_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.user_id
	 * @param userId  the value for word_shopping_cart.user_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.resoure_type
	 * @return  the value of word_shopping_cart.resoure_type
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public String getResoureType() {
		return resoureType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.resoure_type
	 * @param resoureType  the value for word_shopping_cart.resoure_type
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setResoureType(String resoureType) {
		this.resoureType = resoureType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.journal_id
	 * @return  the value of word_shopping_cart.journal_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public Integer getJournalId() {
		return journalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.journal_id
	 * @param journalId  the value for word_shopping_cart.journal_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setJournalId(Integer journalId) {
		this.journalId = journalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.article_id
	 * @return  the value of word_shopping_cart.article_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.article_id
	 * @param articleId  the value for word_shopping_cart.article_id
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.pay_flag
	 * @return  the value of word_shopping_cart.pay_flag
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public Integer getPayFlag() {
		return payFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.pay_flag
	 * @param payFlag  the value for word_shopping_cart.pay_flag
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setPayFlag(Integer payFlag) {
		this.payFlag = payFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column word_shopping_cart.create_time
	 * @return  the value of word_shopping_cart.create_time
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column word_shopping_cart.create_time
	 * @param createTime  the value for word_shopping_cart.create_time
	 * @mbggenerated  Fri Dec 18 15:37:48 GMT+08:00 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	private String articleName;
	private String journalName;
	private Double articlePrice;
	private Double journalPrice;
	private String cover;
	private String type;
	private String flag ="0";
	public String getArticleName() {
		return articleName;
	}
	
	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	public String getJournalName() {
		return journalName;
	}

	public void setJournalName(String journalName) {
		this.journalName = journalName;
	}

	public Double getArticlePrice() {
		return articlePrice;
	}

	public void setArticlePrice(Double articlePrice) {
		this.articlePrice = articlePrice;
	}

	public Double getJournalPrice() {
		return journalPrice;
	}

	public void setJournalPrice(Double journalPrice) {
		this.journalPrice = journalPrice;
	}

	public String getCover() {
		return cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		if(flag!=null && !flag.equals("")){
			this.flag = flag;
		}
	}
}