package com.database.bean;

import java.io.Serializable;

public class WordUsersKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_users.user_account
     *
     * @mbggenerated Wed Jul 01 10:00:17 GMT+08:00 2015
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_users.user_id
     *
     * @mbggenerated Wed Jul 01 10:00:17 GMT+08:00 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_users.user_account
     *
     * @return the value of word_users.user_account
     *
     * @mbggenerated Wed Jul 01 10:00:17 GMT+08:00 2015
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_users.user_account
     *
     * @param userAccount the value for word_users.user_account
     *
     * @mbggenerated Wed Jul 01 10:00:17 GMT+08:00 2015
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_users.user_id
     *
     * @return the value of word_users.user_id
     *
     * @mbggenerated Wed Jul 01 10:00:17 GMT+08:00 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_users.user_id
     *
     * @param userId the value for word_users.user_id
     *
     * @mbggenerated Wed Jul 01 10:00:17 GMT+08:00 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public WordUsersKey(){
    	
    }
    public WordUsersKey(String userAccount,Integer userId){
    	this.userAccount=userAccount;
    	this.userId=userId;
    }
}