package com.database.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WordJournalExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected Integer limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected Integer limitEnd;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public WordJournalExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public Integer getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public Integer getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSkipIsNull() {
			addCriterion("skip is null");
			return (Criteria) this;
		}

		public Criteria andSkipIsNotNull() {
			addCriterion("skip is not null");
			return (Criteria) this;
		}

		public Criteria andSkipEqualTo(String value) {
			addCriterion("skip =", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipNotEqualTo(String value) {
			addCriterion("skip <>", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipGreaterThan(String value) {
			addCriterion("skip >", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipGreaterThanOrEqualTo(String value) {
			addCriterion("skip >=", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipLessThan(String value) {
			addCriterion("skip <", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipLessThanOrEqualTo(String value) {
			addCriterion("skip <=", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipLike(String value) {
			addCriterion("skip like", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipNotLike(String value) {
			addCriterion("skip not like", value, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipIn(List<String> values) {
			addCriterion("skip in", values, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipNotIn(List<String> values) {
			addCriterion("skip not in", values, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipBetween(String value1, String value2) {
			addCriterion("skip between", value1, value2, "skip");
			return (Criteria) this;
		}

		public Criteria andSkipNotBetween(String value1, String value2) {
			addCriterion("skip not between", value1, value2, "skip");
			return (Criteria) this;
		}

		public Criteria andLabelIsNull() {
			addCriterion("label is null");
			return (Criteria) this;
		}

		public Criteria andLabelIsNotNull() {
			addCriterion("label is not null");
			return (Criteria) this;
		}

		public Criteria andLabelEqualTo(String value) {
			addCriterion("label =", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotEqualTo(String value) {
			addCriterion("label <>", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelGreaterThan(String value) {
			addCriterion("label >", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelGreaterThanOrEqualTo(String value) {
			addCriterion("label >=", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLessThan(String value) {
			addCriterion("label <", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLessThanOrEqualTo(String value) {
			addCriterion("label <=", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLike(String value) {
			addCriterion("label like", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotLike(String value) {
			addCriterion("label not like", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelIn(List<String> values) {
			addCriterion("label in", values, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotIn(List<String> values) {
			addCriterion("label not in", values, "label");
			return (Criteria) this;
		}

		public Criteria andLabelBetween(String value1, String value2) {
			addCriterion("label between", value1, value2, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotBetween(String value1, String value2) {
			addCriterion("label not between", value1, value2, "label");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andCoverIsNull() {
			addCriterion("cover is null");
			return (Criteria) this;
		}

		public Criteria andCoverIsNotNull() {
			addCriterion("cover is not null");
			return (Criteria) this;
		}

		public Criteria andCoverEqualTo(String value) {
			addCriterion("cover =", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverNotEqualTo(String value) {
			addCriterion("cover <>", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverGreaterThan(String value) {
			addCriterion("cover >", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverGreaterThanOrEqualTo(String value) {
			addCriterion("cover >=", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverLessThan(String value) {
			addCriterion("cover <", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverLessThanOrEqualTo(String value) {
			addCriterion("cover <=", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverLike(String value) {
			addCriterion("cover like", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverNotLike(String value) {
			addCriterion("cover not like", value, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverIn(List<String> values) {
			addCriterion("cover in", values, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverNotIn(List<String> values) {
			addCriterion("cover not in", values, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverBetween(String value1, String value2) {
			addCriterion("cover between", value1, value2, "cover");
			return (Criteria) this;
		}

		public Criteria andCoverNotBetween(String value1, String value2) {
			addCriterion("cover not between", value1, value2, "cover");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("type_id is null");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("type_id is not null");
			return (Criteria) this;
		}

		public Criteria andTypeIdEqualTo(Integer value) {
			addCriterion("type_id =", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotEqualTo(Integer value) {
			addCriterion("type_id <>", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThan(Integer value) {
			addCriterion("type_id >", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("type_id >=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThan(Integer value) {
			addCriterion("type_id <", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("type_id <=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIn(List<Integer> values) {
			addCriterion("type_id in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotIn(List<Integer> values) {
			addCriterion("type_id not in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("type_id between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("type_id not between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andPassTypeIsNull() {
			addCriterion("pass_type is null");
			return (Criteria) this;
		}

		public Criteria andPassTypeIsNotNull() {
			addCriterion("pass_type is not null");
			return (Criteria) this;
		}

		public Criteria andPassTypeEqualTo(String value) {
			addCriterion("pass_type =", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeNotEqualTo(String value) {
			addCriterion("pass_type <>", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeGreaterThan(String value) {
			addCriterion("pass_type >", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeGreaterThanOrEqualTo(String value) {
			addCriterion("pass_type >=", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeLessThan(String value) {
			addCriterion("pass_type <", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeLessThanOrEqualTo(String value) {
			addCriterion("pass_type <=", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeLike(String value) {
			addCriterion("pass_type like", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeNotLike(String value) {
			addCriterion("pass_type not like", value, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeIn(List<String> values) {
			addCriterion("pass_type in", values, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeNotIn(List<String> values) {
			addCriterion("pass_type not in", values, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeBetween(String value1, String value2) {
			addCriterion("pass_type between", value1, value2, "passType");
			return (Criteria) this;
		}

		public Criteria andPassTypeNotBetween(String value1, String value2) {
			addCriterion("pass_type not between", value1, value2, "passType");
			return (Criteria) this;
		}

		public Criteria andEsIdIsNull() {
			addCriterion("es_id is null");
			return (Criteria) this;
		}

		public Criteria andEsIdIsNotNull() {
			addCriterion("es_id is not null");
			return (Criteria) this;
		}

		public Criteria andEsIdEqualTo(String value) {
			addCriterion("es_id =", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdNotEqualTo(String value) {
			addCriterion("es_id <>", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdGreaterThan(String value) {
			addCriterion("es_id >", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdGreaterThanOrEqualTo(String value) {
			addCriterion("es_id >=", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdLessThan(String value) {
			addCriterion("es_id <", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdLessThanOrEqualTo(String value) {
			addCriterion("es_id <=", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdLike(String value) {
			addCriterion("es_id like", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdNotLike(String value) {
			addCriterion("es_id not like", value, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdIn(List<String> values) {
			addCriterion("es_id in", values, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdNotIn(List<String> values) {
			addCriterion("es_id not in", values, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdBetween(String value1, String value2) {
			addCriterion("es_id between", value1, value2, "esId");
			return (Criteria) this;
		}

		public Criteria andEsIdNotBetween(String value1, String value2) {
			addCriterion("es_id not between", value1, value2, "esId");
			return (Criteria) this;
		}

		public Criteria andPassUseridIsNull() {
			addCriterion("pass_userId is null");
			return (Criteria) this;
		}

		public Criteria andPassUseridIsNotNull() {
			addCriterion("pass_userId is not null");
			return (Criteria) this;
		}

		public Criteria andPassUseridEqualTo(Integer value) {
			addCriterion("pass_userId =", value, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridNotEqualTo(Integer value) {
			addCriterion("pass_userId <>", value, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridGreaterThan(Integer value) {
			addCriterion("pass_userId >", value, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("pass_userId >=", value, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridLessThan(Integer value) {
			addCriterion("pass_userId <", value, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridLessThanOrEqualTo(Integer value) {
			addCriterion("pass_userId <=", value, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridIn(List<Integer> values) {
			addCriterion("pass_userId in", values, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridNotIn(List<Integer> values) {
			addCriterion("pass_userId not in", values, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridBetween(Integer value1, Integer value2) {
			addCriterion("pass_userId between", value1, value2, "passUserid");
			return (Criteria) this;
		}

		public Criteria andPassUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("pass_userId not between", value1, value2,
					"passUserid");
			return (Criteria) this;
		}

		public Criteria andPassTimeIsNull() {
			addCriterion("pass_time is null");
			return (Criteria) this;
		}

		public Criteria andPassTimeIsNotNull() {
			addCriterion("pass_time is not null");
			return (Criteria) this;
		}

		public Criteria andPassTimeEqualTo(Date value) {
			addCriterion("pass_time =", value, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeNotEqualTo(Date value) {
			addCriterion("pass_time <>", value, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeGreaterThan(Date value) {
			addCriterion("pass_time >", value, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pass_time >=", value, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeLessThan(Date value) {
			addCriterion("pass_time <", value, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeLessThanOrEqualTo(Date value) {
			addCriterion("pass_time <=", value, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeIn(List<Date> values) {
			addCriterion("pass_time in", values, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeNotIn(List<Date> values) {
			addCriterion("pass_time not in", values, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeBetween(Date value1, Date value2) {
			addCriterion("pass_time between", value1, value2, "passTime");
			return (Criteria) this;
		}

		public Criteria andPassTimeNotBetween(Date value1, Date value2) {
			addCriterion("pass_time not between", value1, value2, "passTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeIsNull() {
			addCriterion("submit_time is null");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeIsNotNull() {
			addCriterion("submit_time is not null");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeEqualTo(Date value) {
			addCriterion("submit_time =", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeNotEqualTo(Date value) {
			addCriterion("submit_time <>", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeGreaterThan(Date value) {
			addCriterion("submit_time >", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("submit_time >=", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeLessThan(Date value) {
			addCriterion("submit_time <", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeLessThanOrEqualTo(Date value) {
			addCriterion("submit_time <=", value, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeIn(List<Date> values) {
			addCriterion("submit_time in", values, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeNotIn(List<Date> values) {
			addCriterion("submit_time not in", values, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeBetween(Date value1, Date value2) {
			addCriterion("submit_time between", value1, value2, "submitTime");
			return (Criteria) this;
		}

		public Criteria andSubmitTimeNotBetween(Date value1, Date value2) {
			addCriterion("submit_time not between", value1, value2,
					"submitTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andHaveDataIsNull() {
			addCriterion("have_data is null");
			return (Criteria) this;
		}

		public Criteria andHaveDataIsNotNull() {
			addCriterion("have_data is not null");
			return (Criteria) this;
		}

		public Criteria andHaveDataEqualTo(String value) {
			addCriterion("have_data =", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataNotEqualTo(String value) {
			addCriterion("have_data <>", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataGreaterThan(String value) {
			addCriterion("have_data >", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataGreaterThanOrEqualTo(String value) {
			addCriterion("have_data >=", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataLessThan(String value) {
			addCriterion("have_data <", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataLessThanOrEqualTo(String value) {
			addCriterion("have_data <=", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataLike(String value) {
			addCriterion("have_data like", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataNotLike(String value) {
			addCriterion("have_data not like", value, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataIn(List<String> values) {
			addCriterion("have_data in", values, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataNotIn(List<String> values) {
			addCriterion("have_data not in", values, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataBetween(String value1, String value2) {
			addCriterion("have_data between", value1, value2, "haveData");
			return (Criteria) this;
		}

		public Criteria andHaveDataNotBetween(String value1, String value2) {
			addCriterion("have_data not between", value1, value2, "haveData");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_journal
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 27 11:17:42 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}