var ZU={name:"\u603b\u4f53\u51fd\u6570",$id:function(a){return document.getElementById(a)},getElementsByTagName:function(a,b){var c=[];a=a.split(",");if(b==null)b=document;for(var f=0,d;d=a[f++];){var e=b.getElementsByTagName(d);e=d=="child"?document.body.childNodes:b.getElementsByTagName(d);d=0;for(var g;g=e[d++];)c.push(g)}return c},msg:function(){},getRandom:function(){return Math.floor(Math.random()*2147483648)},removeChild:function(a){try{a!=null&&a.parentNode.removeChild(a)}catch(b){}},getSplitArticleId:function(a){return parseInt(a.id.split("_")[6],
10)},getSplitOrder:function(a){return parseInt(a.id.split("_")[2],10)},getSplitId:function(a){return typeof a=="object"?a.id.split("_")[3]:a.split("_")[3]},getEndImg:function(a){a=a.getElementsByTagName("img");var b=null;if(a.length>0)b=a[a.length-1];return b},getEnd1Img:function(a){a=a.getElementsByTagName("img");var b=null;if(a.length>1)b=a[a.length-2];return b},getEnd2Img:function(a){a=a.getElementsByTagName("img");var b=null;if(a.length>1)b=a[a.length-3];return b},location:function(){},getMouseXY:function(a){a=
a||window.event;var b=document.documentElement.scrollLeft||document.body.scrollLeft,c=document.documentElement.scrollTop||document.body.scrollTop;return{x:a.pageX||a.clientX+b,y:a.pageY||a.clientY+c}},getNodeOffset:function(a,b){var c={};if(a==null)return c;c.top=a.offsetTop;c.left=a.offsetLeft;c.width=a.offsetWidth;c.height=a.offsetHeight;try{if(b!=null){c.top-=b.scrollTop;c.left-=b.scrollLeft}for(;a=a.offsetParent;){c.top+=a.offsetTop;c.left+=a.offsetLeft}}catch(f){console.info("error="+f)}return c},
textContent:function(a){return a.textContent?a.textContent:a.innerText},getHLevel:function(a){return a!=null&&a.nodeType==1&&/H\d{1}/.test(a.nodeName)?parseInt(a.nodeName.substring(1,2),10):0},inner:function(a,b){a=this.getNodeOffset(a);return b.x>a.left&&b.x<a.left+a.width&&b.y>a.top&&b.y<a.top+a.height?b.y<a.top+a.height/2?1:2:0},innerJson:function(a,b){var c={};a=this.getNodeOffset(a);if(b.x>a.left&&b.x<a.left+a.width&&b.y>a.top&&b.y<a.top+a.height){if(b.y<a.top+a.height/2)c.up=true;else c.down=
true;if(b.x<a.left+a.width/2)c.left=true;else c.right=true;c["in"]=true}else c.out=true;return c},clearHtml:function(a){return a.replace(/<.+?>/gim,"")},setCookie:function(a,b){document.cookie=a+"="+escape(b)+";path=/"},getCookie:function(a){for(var b=document.cookie.split("; "),c=0;c<b.length;c++){var f=b[c].split("=");if(a==f[0])return unescape(f[1])}return null},delCookie:function(a){setCookie(a,"")},delAllCookie:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++)for(var c=a[b].split("="),
f=0;f<c.length;f++)setCookie(c[0],"")},timeToStamp:function(a){return timestamp=a.getTime()},stampToTime:function(a){return new Date(a)},strToTime:function(a){return new Date(a)},timeToStr:function(a){var b=a.getFullYear(),c=a.getMonth()+1,f=a.getDate(),d=a.getHours(),e=a.getMinutes();a=a.getSeconds();c=(c<10?"0":"")+c;f=(f<10?"0":"")+f;d=(d<10?"0":"")+d;e=(e<10?"0":"")+e;a=(a<10?"0":"")+a;return b+"-"+c+"-"+f+" "+d+":"+e+":"+a},stampToTimeStr:function(a){return this.timeToStr(this.stampToTime(a))},
stampToTimeStr1:function(a){var b=this.stampToTime(a);a=b.getFullYear();var c=b.getMonth()+1,f=b.getDate(),d=b.getHours();b=b.getMinutes();c=(c<10?"0":"")+c;f=(f<10?"0":"")+f;d=(d<10?"0":"")+d;b=(b<10?"0":"")+b;return a+"-"+c+"-"+f+" "+d+":"+b},getParameter:function(a){var b=window.location.search,c=a.length;a=b.indexOf(a);if(a==-1)return"";a+=c+1;c=b.indexOf("&",a);if(c==-1)return b.substring(a);return b.substring(a,c)},getParam:function(a,b){if(b==null)return"";if(b.length==0)return"";else{var c=
a.length;a=b.indexOf(a);if(a==-1)return"";a+=c+1;c=b.indexOf("&",a);if(c==-1)return b.substring(a);return b.substring(a,c)}},jsonToUrl:function(a){var b="";for(var c in a)b+=c+"="+a[c]+"&";return encodeURI(b)},extend:function(a,b,c){if(b)for(var f in b)if(!c||!a.hasOwnProperty(f))a[f]=b[f];return a},indexOf:function(a,b,c){var f=-1;c=this.isNumber(c)?c:0;this.each(a,function(d,e){if(e>=c&&d===b){f=e;return false}});return f},each:function(a,b,c){if(a!=null)if(a.length===+a.length)for(var f=0,d=a.length;f<
d;f++){if(b.call(c,a[f],f,a)===false)return false}else for(f in a)if(a.hasOwnProperty(f))if(b.call(c,a[f],f,a)===false)return false},isArray:function(a){return Object.prototype.toString.apply(a)=="[object Array]"},isNumber:function(a){return Object.prototype.toString.apply(a)=="[object Number]"},trim:function(a){return a.replace(/(^[ \t\n\r]+)|([ \t\n\r]+$)/g,"")},on:function(a,b,c){var f=this.isArray(b)?b:this.trim(b).split(/\s+/),d=f.length;if(d)for(;d--;){b=f[d];if(a.addEventListener)a.addEventListener(b,
c,false);else{if(!c._d)c._d={els:[]};var e=b+c.toString(),g=this.indexOf(c._d.els,a);if(!c._d[e]||g==-1){g==-1&&c._d.els.push(a);c._d[e]||(c._d[e]=function(j){return c.call(j.srcElement,j||window.event)});a.attachEvent("on"+b,c._d[e])}}}a=null},un:function(a,b,c){var f=this.isArray(b)?b:this.trim(b).split(/\s+/),d=f.length;if(d)for(;d--;){b=f[d];if(a.removeEventListener)a.removeEventListener(b,c,false);else{var e=b+c.toString();try{a.detachEvent("on"+b,c._d?c._d[e]:c)}catch(g){}if(c._d&&c._d[e]){b=
this.indexOf(c._d.els,a);b!=-1&&c._d.els.splice(b,1);c._d.els.length==0&&delete c._d[e]}}}},Ajax:function(){function a(d,e){function g(){}e=e||{};var j=e.async!==false,h=e.method||"GET",k=e.type||"json",l=e.encode||"UTF-8",n=e.timeout||6E3,o=e.data||null,s=e.success||g,p=e.failure||g;h=h.toUpperCase();if(o&&typeof o=="object")o=b(o);if(h=="GET"&&o){d+=(d.indexOf("?")==-1?"?":"&")+o;o=null}var m=function(){try{return new XMLHttpRequest}catch(u){try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(v){try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(t){p(null,
"create xhr failed",t)}}}}();if(m){var q=false,r;if(j&&n>0)r=setTimeout(function(){m.abort();q=true},n);m.onreadystatechange=function(){if(m.readyState==4&&!q){f(m,k,s,p);clearTimeout(r);m=null}};m.open(h,d,j);h=="POST"&&m.setRequestHeader("Content-type","application/x-www-form-urlencoded;charset="+l);m.setRequestHeader("x-requested-with","XMLHttpRequest");m.send(o);return m}}function b(d){var e=[];for(var g in d){var j=d[g];if(j.constructor==Array)for(var h=0,k=j.length;h<k;h++)e.push(g+"="+encodeURIComponent(j[h]));
else e.push(g+"="+encodeURIComponent(j))}return e.join("&")}function c(d){return eval("("+d+")")}function f(d,e,g,j){var h=d.status,k;if(h>=200&&h<300){h=d.getResponseHeader("sessionstatus");if(h=="reload"||h=="timeout")j(d,h);else{switch(e){case "text":k=d.responseText;break;case "json":k=function(l){try{return c(l)}catch(n){try{return(new Function("return "+l))()}catch(o){j(d,"parse json error",o)}}}(d.responseText);break;case "xml":k=d.responseXML;break}typeof k!=="undefined"&&g(k)}}else h===0?
j(d,"request timeout"):j(d,d.status);d=null}return function(){for(var d={request:a},e=["text","json","xml"],g=0,j=e.length;g<j;g++)d[e[g]]=function(h){return function(k,l){l=l||{};l.type=e[h];return a(k,l)}}(g);return d}()}(),getPreHNode:function(a){if(a==null)return null;var b=null,c=a;do{var f=c.previousSibling;c=f==null?c.parentNode:f;if(c==null||a.nodeType==9){b=null;break}if(ZU.getHLevel(c)>0){b=c;break}}while(1);return b},getPreNodeH:function(a){if(a==null)return null;for(var b=document.body.getElementsByTagName("*"),
c=null,f=0;f<b.length;f++){var d=b[f];if(d!=null&&d.nodeType==1){if(d==a)break;if(/H\d{1}/.test(d.nodeName))c=d}}return c}};function getAllHnode(a){var b=document;if(a!=null)a=document.getElementById(a);a=document.getElementsByTagName("*");b=[];for(var c=0;c<a.length;c++){var f=a[c];if(f.nodeType==1){var d=ZU.getHLevel(f);if(d!=0)if(d>0&&d<7){var e={};e.idStr=f.id;e.text=ZU.textContent(f);e.order=d;e.icon="normal";b.push(e)}}}return b}
function getAllHnode1(a){function b(l){for(var n=0;n<d.length;n++)if(d[n](l))return n+1;return-1}var c=document.body;if(a!=null){a=getElementById(a);if(a!=null)c=a}a=[];for(var f=[],d=["h1","h2","h3","h4","h5","h6"],e=0;e<d.length;e++)if(typeof d[e]=="string")d[e]=function(l){return function(n){return n.tagName==l.toUpperCase()}}(d[e]);else if(typeof d[e]!="function")d[e]=function(l){return null};c=c.childNodes;e=0;for(var g=c.length;e<g;e++){var j=c[e],h=b(j);if(h>=0){var k={};k.idStr=j.id;k.text=
j.innerText;k.order=h;a.push(k);f.push(k)}}return a}function ueSetParagraphFoucs(a){if(a>7)return false;for(var b=0;b<7;b++)ZU.$id("toolTitle"+b).className=b==a?"liactive":""}function ueParagraph(a){if(a=="p")$EDITORUI.edui85.onclick();else{ue.execCommand("removeformat","","","");ue.execCommand("Paragraph",a,{})}}
function ueFontsize(a){for(var b=ue.options.fontsize,c=ue.queryCommandValue("fontsize"),f=0,d=0,e=0;e<b.length;e++)if(c==b[e]+"px"){d=e;break}if(a=="add"){if(d<b.length-1)f=b[d+1]}else if(d>0)f=b[d-1];f!=0&&ue.execCommand("fontsize",f+"px")}function ueCopy(){var a=ue.selection.getRange();if(!a.collapsed){a.select();ue.execCommand("copy")}}function uePaste(){ue.execCommand("paste")}
if(!window.console){window.console={};for(var methods=["log","debug","info","warn","error","assert","dir","dirxml","group","groupEnd","time","timeEnd","count","trace","profile","profileEnd"],noop=function(){},i=0,method;method=methods[i++];)window.console[method]=noop};
