package com.database.dao;

import com.database.bean.Alipayasynchronouslog;
import com.database.bean.AlipayasynchronouslogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlipayasynchronouslogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int countByExample(AlipayasynchronouslogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int deleteByExample(AlipayasynchronouslogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int insert(Alipayasynchronouslog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int insertSelective(Alipayasynchronouslog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	List<Alipayasynchronouslog> selectByExample(
			AlipayasynchronouslogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	Alipayasynchronouslog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Alipayasynchronouslog record,
			@Param("example") AlipayasynchronouslogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int updateByExample(@Param("record") Alipayasynchronouslog record,
			@Param("example") AlipayasynchronouslogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int updateByPrimaryKeySelective(Alipayasynchronouslog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table alipayasynchronouslog
	 * @mbggenerated  Mon Dec 21 14:55:29 CST 2015
	 */
	int updateByPrimaryKey(Alipayasynchronouslog record);
}