package com.database.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.database.bean.Article;
import com.database.bean.ArticleExample;
import com.web.homePage.bean.KnowPlate;
import com.web.view.bean.JournalInfoBean;
import com.web.word.bean.ArticleAndContent;
import com.web.word.bean.NodeBean;
import com.web.word.bean.NodeContentBean;

public interface ArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int countByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int deleteByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int deleteByPrimaryKey(Integer articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int insertSelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	List<Article> selectByExample(ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	Article selectByPrimaryKey(Integer articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Article record,
			@Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int updateByExample(@Param("record") Article record,
			@Param("example") ArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int updateByPrimaryKeySelective(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_article
	 * @mbggenerated  Thu Jan 07 10:31:08 CST 2016
	 */
	int updateByPrimaryKey(Article record);

	/**
	 * @param articleId
	 */
	void updateArticleTime(Integer articleId);
	
	Article checkArticleName(Article bean);
	
	Article submitCheckArticleName(Article bean);
	
	int articleIsBelongMe(Article bean);
	
	int updateArticle(ArticleAndContent articleAndContent);
	
	int insertKeyword(ArticleAndContent articleAndContent);
	
	int insertUpadateArtPlate(ArticleAndContent articleAndContent);
	
	int updateArticleSaveStatus(Integer articleId);
	
	int updateArticleStatus(HashMap<String,Object> hashMap);
	
	void insertNewArticle(Article bean);
	
	String getArticleStyle(Integer articleId);
	
	List<NodeBean> selectNodeTempByArticleId(NodeBean nodeBean);
	
	List<NodeContentBean> selectContentTempByArticleId(NodeContentBean nodeBean);
	
	void updateArticleDownTime(Integer articleId);
	
	List<KnowPlate> queryAllPlate(Integer pid);
	
	int updateArticleName(Article record);
	
	List<Article> selectArticleLike(HashMap<String,Object> hashMap);
	
	List<JournalInfoBean> getJournalInfo(JournalInfoBean journalInfoBean);

	List<Article> getRecommendJournal(Map<String, String> map);
	
	int searchArticleByResourceCount(Article bean);
	List<Article> searchArticleByResource(Article bean);
}