package com.database.dao;

import com.database.bean.ArticleProperty;
import com.database.bean.ArticlePropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlePropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int countByExample(ArticlePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int deleteByExample(ArticlePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int deleteByPrimaryKey(Integer articlePropertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int insert(ArticleProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int insertSelective(ArticleProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    List<ArticleProperty> selectByExample(ArticlePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    ArticleProperty selectByPrimaryKey(Integer articlePropertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") ArticleProperty record, @Param("example") ArticlePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int updateByExample(@Param("record") ArticleProperty record, @Param("example") ArticlePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int updateByPrimaryKeySelective(ArticleProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_article_property
     *
     * @mbggenerated Fri Apr 10 13:43:36 CST 2015
     */
    int updateByPrimaryKey(ArticleProperty record);
    
    void updateGlobalProperty(ArticleProperty record);
    
    void saveGlobalSetting(ArticleProperty record);
    
    ArticleProperty getGlobalSetting(Integer articleId);
    
    ArticleProperty getOutlineSetting(Integer articleId);
    
    ArticleProperty getOutlineByArticleId(Integer articleId);
    
    void updateOutlineProperty(ArticleProperty record);
    
    void saveOutlineSetting(ArticleProperty record);
}