package com.database.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.database.bean.Ascondition;
import com.database.bean.AsconditionExample;
import com.web.document.bean.AdvancedSearchConditionBean;

public interface AsconditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int countByExample(AsconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int deleteByExample(AsconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int deleteByPrimaryKey(Integer asconditionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int insert(Ascondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int insertSelective(Ascondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    List<Ascondition> selectByExample(AsconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    Ascondition selectByPrimaryKey(Integer asconditionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ascondition record, @Param("example") AsconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int updateByExample(@Param("record") Ascondition record, @Param("example") AsconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int updateByPrimaryKeySelective(Ascondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_ascondition
     *
     * @mbggenerated Wed Apr 29 16:58:02 CST 2015
     */
    int updateByPrimaryKey(Ascondition record);
    
    int insertAdvCondition(AdvancedSearchConditionBean bean);
    
    List<AdvancedSearchConditionBean> searchAdvCondition(Map<String,Object> map);
    
    void deleteOrdCondition(Map<String,Object> map);
    
    void deleteAdvCondition(Integer id);
    
    void updateAdvCondition(AdvancedSearchConditionBean asBean);
}