package com.database.dao;

import com.database.bean.ContentWhole;
import com.database.bean.ContentWholeExample;
import com.database.bean.ContentWithBLOBs;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentWholeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int countByExample(ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int deleteByExample(ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int deleteByPrimaryKey(Integer wholeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int insert(ContentWhole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int insertSelective(ContentWhole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	List<ContentWhole> selectByExampleWithBLOBs(ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	List<ContentWhole> selectByExample(ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	ContentWhole selectByPrimaryKey(Integer wholeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ContentWhole record,
			@Param("example") ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") ContentWhole record,
			@Param("example") ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int updateByExample(@Param("record") ContentWhole record,
			@Param("example") ContentWholeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int updateByPrimaryKeySelective(ContentWhole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(ContentWhole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_whole
	 * @mbggenerated  Tue Apr 07 14:40:31 CST 2015
	 */
	int updateByPrimaryKey(ContentWhole record);
	
	void saveContent(ContentWhole record);
	
	List<ContentWithBLOBs> selectContentByArticleId(ContentWhole temp);
}