package com.database.dao;

import com.database.bean.Content;
import com.database.bean.ContentExample;
import com.database.bean.ContentWithBLOBs;
import com.web.document.bean.GrabContent;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int countByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int deleteByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int deleteByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int insert(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int insertSelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    List<ContentWithBLOBs> selectByExampleWithBLOBs(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    List<Content> selectByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    ContentWithBLOBs selectByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") ContentWithBLOBs record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ContentWithBLOBs record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int updateByPrimaryKeySelective(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_content
     *
     * @mbggenerated Wed Apr 29 11:52:28 CST 2015
     */
    int updateByPrimaryKey(Content record);
    
    /**
     * 保存内容
     * <p>Title: saveContent</p> 
     * <p>Description: TODO</p>
     * @param content
     * @return
     */
    int saveContent(ContentWithBLOBs content);
    
    /**
     * 根据id抓取新闻
     * <p>Title: queryGrabContentText</p> 
     * <p>Description: TODO</p>
     * @param crawlId
     * @return
     */
    GrabContent queryGrabContentText(int crawlId);
    
    /**
     * 根据内容id查询新内容
     * <p>Title: selectnewContent</p> 
     * <p>Description: TODO</p>
     * @param contentId
     * @return
     */
    com.lucene.entity.doc.Content selectnewContent(int contentId);
    
    
    ContentWithBLOBs getCrawlByContentId(Integer crawlId);
}