package com.database.dao;

import com.database.bean.Crawl;
import com.database.bean.CrawlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int countByExample(CrawlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int deleteByExample(CrawlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int deleteByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int insert(Crawl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int insertSelective(Crawl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    List<Crawl> selectByExample(CrawlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    Crawl selectByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") Crawl record, @Param("example") CrawlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int updateByExample(@Param("record") Crawl record, @Param("example") CrawlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int updateByPrimaryKeySelective(Crawl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Thu May 07 15:43:33 CST 2015
     */
    int updateByPrimaryKey(Crawl record);
}