package com.database.dao;

import com.database.bean.Homepage;
import com.database.bean.HomepageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomepageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int countByExample(HomepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int deleteByExample(HomepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int deleteByPrimaryKey(Integer homepagePropertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int insert(Homepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int insertSelective(Homepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    List<Homepage> selectByExample(HomepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    Homepage selectByPrimaryKey(Integer homepagePropertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int updateByExampleSelective(@Param("record") Homepage record, @Param("example") HomepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int updateByExample(@Param("record") Homepage record, @Param("example") HomepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int updateByPrimaryKeySelective(Homepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_homepage_property
     *
     * @mbggenerated Tue May 05 16:56:37 CST 2015
     */
    int updateByPrimaryKey(Homepage record);
    
    void deleteHomePageSetting(Integer articleId);
    
    Homepage selectByArticleId(Integer articleId);
}