package com.database.dao;

import com.database.bean.KnowPlate;
import com.database.bean.KnowPlateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KnowPlateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int countByExample(KnowPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int deleteByExample(KnowPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int deleteByPrimaryKey(Integer plateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int insert(KnowPlate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int insertSelective(KnowPlate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    List<KnowPlate> selectByExample(KnowPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    KnowPlate selectByPrimaryKey(Integer plateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") KnowPlate record, @Param("example") KnowPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int updateByExample(@Param("record") KnowPlate record, @Param("example") KnowPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int updateByPrimaryKeySelective(KnowPlate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_plate
     *
     * @mbggenerated Wed May 06 17:24:35 CST 2015
     */
    int updateByPrimaryKey(KnowPlate record);
    
    KnowPlate getArticlePlate(Integer articleId);
}