package com.database.dao;

import com.database.bean.KnowNopassReason;
import com.database.bean.KnowNopassReasonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KnowNopassReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int countByExample(KnowNopassReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int deleteByExample(KnowNopassReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer nopassReasonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int insert(KnowNopassReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int insertSelective(KnowNopassReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    List<KnowNopassReason> selectByExample(KnowNopassReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    KnowNopassReason selectByPrimaryKey(Integer nopassReasonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") KnowNopassReason record, @Param("example") KnowNopassReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int updateByExample(@Param("record") KnowNopassReason record, @Param("example") KnowNopassReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(KnowNopassReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table know_nopass_reason
     *
     * @mbggenerated Fri Jul 17 11:26:55 GMT+08:00 2015
     */
    int updateByPrimaryKey(KnowNopassReason record);
}