package com.database.dao;

import com.database.bean.NewsPic;
import com.database.bean.NewsPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsPicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int countByExample(NewsPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int deleteByExample(NewsPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int insert(NewsPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int insertSelective(NewsPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	List<NewsPic> selectByExample(NewsPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	NewsPic selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") NewsPic record,
			@Param("example") NewsPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int updateByExample(@Param("record") NewsPic record,
			@Param("example") NewsPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int updateByPrimaryKeySelective(NewsPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_pic
	 * @mbggenerated  Fri Mar 04 09:49:36 CST 2016
	 */
	int updateByPrimaryKey(NewsPic record);
}