package com.database.dao;

import com.database.bean.NewsColumnGroup;
import com.database.bean.NewsColumnGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsColumnGroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int countByExample(NewsColumnGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int deleteByExample(NewsColumnGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int insert(NewsColumnGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int insertSelective(NewsColumnGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	List<NewsColumnGroup> selectByExample(NewsColumnGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	NewsColumnGroup selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") NewsColumnGroup record,
			@Param("example") NewsColumnGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") NewsColumnGroup record,
			@Param("example") NewsColumnGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(NewsColumnGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_column_group
	 * @mbggenerated  Wed Feb 24 10:49:18 GMT+08:00 2016
	 */
	int updateByPrimaryKey(NewsColumnGroup record);
}