package com.database.dao;

import com.database.bean.NewsColumnType;
import com.database.bean.NewsColumnTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsColumnTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int countByExample(NewsColumnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int deleteByExample(NewsColumnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int insert(NewsColumnType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int insertSelective(NewsColumnType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    List<NewsColumnType> selectByExample(NewsColumnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    NewsColumnType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") NewsColumnType record, @Param("example") NewsColumnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int updateByExample(@Param("record") NewsColumnType record, @Param("example") NewsColumnTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(NewsColumnType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_column_type
     *
     * @mbggenerated Wed Feb 24 10:59:49 GMT+08:00 2016
     */
    int updateByPrimaryKey(NewsColumnType record);
}