package com.database.dao;

import com.database.bean.User;
import com.database.bean.UserExample;
import com.database.bean.UserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    User selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_users
     *
     * @mbggenerated Tue Apr 07 14:40:31 CST 2015
     */
    int updateByPrimaryKey(User record);
}