package com.database.dao;

import com.database.bean.UserOtherInfo;
import com.database.bean.UserOtherInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOtherInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int countByExample(UserOtherInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int deleteByExample(UserOtherInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int insert(UserOtherInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int insertSelective(UserOtherInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	List<UserOtherInfo> selectByExample(UserOtherInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	UserOtherInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int updateByExampleSelective(@Param("record") UserOtherInfo record,
			@Param("example") UserOtherInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int updateByExample(@Param("record") UserOtherInfo record,
			@Param("example") UserOtherInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int updateByPrimaryKeySelective(UserOtherInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_other_info
	 * @mbggenerated  Wed Dec 09 09:37:41 CST 2015
	 */
	int updateByPrimaryKey(UserOtherInfo record);
}