package com.database.dao;

import com.database.bean.UserSaveContent;
import com.database.bean.UserSaveContentExample;
import com.database.bean.UserSaveContentWithBLOBs;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserSaveContentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int countByExample(UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int deleteByExample(UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int deleteByPrimaryKey(Integer contentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int insert(UserSaveContentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int insertSelective(UserSaveContentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	List<UserSaveContentWithBLOBs> selectByExampleWithBLOBs(
			UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	List<UserSaveContent> selectByExample(UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	UserSaveContentWithBLOBs selectByPrimaryKey(Integer contentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int updateByExampleSelective(
			@Param("record") UserSaveContentWithBLOBs record,
			@Param("example") UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int updateByExampleWithBLOBs(
			@Param("record") UserSaveContentWithBLOBs record,
			@Param("example") UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int updateByExample(@Param("record") UserSaveContent record,
			@Param("example") UserSaveContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int updateByPrimaryKeySelective(UserSaveContentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(UserSaveContentWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table know_content
	 * @mbggenerated  Sat Oct 10 09:50:50 CST 2015
	 */
	int updateByPrimaryKey(UserSaveContent record);

	UserSaveContent getUserSaveContentByUserIdAndContentId(@Param("userId")int userId,@Param("esId")String esId);
}