package com.database.dao;

import com.database.bean.VerifyDoc;
import com.database.bean.VerifyDocExample;
import com.database.bean.VerifyDocWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerifyDocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int countByExample(VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int deleteByExample(VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int insert(VerifyDocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int insertSelective(VerifyDocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    List<VerifyDocWithBLOBs> selectByExampleWithBLOBs(VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    List<VerifyDoc> selectByExample(VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    VerifyDocWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") VerifyDocWithBLOBs record, @Param("example") VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") VerifyDocWithBLOBs record, @Param("example") VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int updateByExample(@Param("record") VerifyDoc record, @Param("example") VerifyDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int updateByPrimaryKeySelective(VerifyDocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(VerifyDocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verifydoc_log
     *
     * @mbggenerated Thu Oct 15 11:13:27 CST 2015
     */
    int updateByPrimaryKey(VerifyDoc record);
    /**
     * 根据esId,增加userCount
     * @param esId
     * @return
     */
    int updateByEsIduserCount(@Param("esId") String esId);
}