package com.database.dao;

import com.database.bean.WordArticleCount;
import com.database.bean.WordArticleCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordArticleCountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int countByExample(WordArticleCountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int deleteByExample(WordArticleCountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int insert(WordArticleCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int insertSelective(WordArticleCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	List<WordArticleCount> selectByExample(WordArticleCountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	WordArticleCount selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") WordArticleCount record,
			@Param("example") WordArticleCountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") WordArticleCount record,
			@Param("example") WordArticleCountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(WordArticleCount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_article_count
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByPrimaryKey(WordArticleCount record);
}