package com.database.dao;

import com.database.bean.WordColumnContact;
import com.database.bean.WordColumnContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordColumnContactMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int countByExample(WordColumnContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int deleteByExample(WordColumnContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int insert(WordColumnContact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int insertSelective(WordColumnContact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	List<WordColumnContact> selectByExample(WordColumnContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	WordColumnContact selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") WordColumnContact record,
			@Param("example") WordColumnContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") WordColumnContact record,
			@Param("example") WordColumnContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(WordColumnContact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_column_contact
	 * @mbggenerated  Tue Oct 27 16:19:21 GMT+08:00 2015
	 */
	int updateByPrimaryKey(WordColumnContact record);
}