package com.database.dao;

import com.database.bean.WordJournal;
import com.database.bean.WordJournalExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface WordJournalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int countByExample(WordJournalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int deleteByExample(WordJournalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int insert(WordJournal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int insertSelective(WordJournal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	List<WordJournal> selectByExample(WordJournalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	WordJournal selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") WordJournal record,
			@Param("example") WordJournalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") WordJournal record,
			@Param("example") WordJournalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(WordJournal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table word_journal
	 * @mbggenerated  Thu Dec 17 10:07:59 GMT+08:00 2015
	 */
	int updateByPrimaryKey(WordJournal record);

	List<WordJournal> getRecommendJournal(Map<String, String> map);
}